### ISSUE TITLE
nvidia.de

### ISSUE THREAD

**Issue by Frozburn** [Hari-Nagarajan/nvidia-bot#1]
Thank you for creating this 🥇  Is it possible to make this work for nvidia.de for a 3090? I've no idea how any of this works

**Comment by Akzyra** [comment]
Change locale to de-de, add `'locale': 'de-de'` to digitalriver requests.

**Comment by Frozburn** [comment]
Thanks. Any idea if the product ID is the same for the nvidia.de 3080 and 3090?

**Comment by Akzyra** [comment]
No, they are different for each country:
RTX_3080_AT = '5440853700'
RTX_3080_DE = '5438792300'

You can check this for details: `https://api.digitalriver.com/v1/shoppers/me/products/5438792300?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=de_DE&format=json`

**Comment by Frozburn** [comment]
Thank you. I assume the ID of the 3090 will become available before we can order? Is that how it worked for the 3080

**Comment by Hari-Nagarajan** [comment]
you wont have to change the product ids, I'm pulling the product ids from digitalriver on start up, just changing the country codes should be enough

**Comment by Frozburn** [comment]
Ah that's nice. I'll first have to figure out how to use this to begin with 👍 Never used anything like this before (total noob)

**Comment by Frozburn** [comment]
Would it be possible to make a mini guide on how to install this thing and make it work? Ngl it's very confusing for a noob that has never used any of this.

**Comment by Nucrates** [comment]
I second Frozburn's question regarding usage. It would be much appreciated as I have spent the last hour and a half trying to figure it out in an effort to avoid bugging you, but I'm at a loss. I have no training haha.

**Comment by Hari-Nagarajan** [comment]
I'm working on making a GUI and an executable for you guys

**Comment by Nucrates** [comment]
thank you so much!

**Comment by Hari-Nagarajan** [comment]
I made a GUI but it was just so.. bad. I made some improvements to the CLI for now though. Having some trouble with pyinstaller (the tool for generating the .exe), theres a bug that makes it have a bunch of antivirus false positives and the .exe just gets removed by windows. 

See: https://github.com/pyinstaller/pyinstaller/issues/4633 and [others](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed)

**Comment by Nucrates** [comment]
Understood, thank you for working on it! I will spend more time trying to learn about this stuff, and check back on the off chance we get lucky with an .exe haha. Last I read, nvidia FE should have some (if only a little) stock some time next week, so I have a few days to learn as much as I can (:

**Comment by BloodredOmega** [comment]
Hi, good job figuring out the API. I just want to point out a issue, maybe it is just for DE and AT local. When you get the id's from the product list there is a problem about the locale. The short names are the same for de and at. So you overwrite the first with the second. In the case of locale=de_de the second is austria so all germans get the wrong id. You need to store both and check in the second call if the long name contains either AT or DE.

Link: https://api.digitalriver.com/v1/shoppers/me/products?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=de_de&format=json&expand=product&fields=product.id,product.displayName,product.pricing&pageNUmber=5
![1](https://user-images.githubusercontent.com/10519566/93662381-f192fa80-fa5f-11ea-897f-f00bb3445745.PNG)

Link: https://api.digitalriver.com/v1/shoppers/me/products/5440853700?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=de_DE&format=json
![2](https://user-images.githubusercontent.com/10519566/93662465-8a297a80-fa60-11ea-9b0e-141692b55d2d.PNG)


in nvidia.py:
![3](https://user-images.githubusercontent.com/10519566/93662528-281d4500-fa61-11ea-8256-c806e6ce400b.PNG)

**Comment by darek292** [comment]
> No, they are different for each country and card:
> RTX_3080_AT = '5440853700'
> RTX_3080_DE = '5438792300'
> 
> Edit: 3090 is not yet listed, only other RTX 30xx entry is the "GeForce NOW 1 year" special.
> 
> You can check this to see if its DE or not: `https://api.digitalriver.com/v1/shoppers/me/products/5438792300?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=de_DE&format=json`

@Akzyra How did you get those IDs? I'm trying to find the UK/GB (en_GB) id for the 3080 but have been unable to. Any help is appreciated.

**Comment by mihaiparvu** [comment]
I think this should work now. Get the latest code and try it :)

**Comment by BloodredOmega** [comment]
Thanks, yes it is fixed. Guess this can be closed now.

**Comment by Zoralback** [comment]
Hello there !

So I tried with the recent locale fixes and doesn't look like fr_fr can make the difference with fr_be cards ,so if I try to input fr_fr I end up with the fr_be model :)

![Sans titre](https://user-images.githubusercontent.com/30176859/93688324-49178180-fac5-11ea-9da4-7a5ac2671e82.png)

here's the fr_fr list : https://api.digitalriver.com/v1/shoppers/me/products?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=fr_fr&format=json&expand=product&fields=product.id,product.displayName,product.pricing&pageNUmber=5  (sometimes the 3080s move to page 6)

Here are the two models :

Fr : https://api.digitalriver.com/v1/shoppers/me/products/5438795200?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=fr_fr&format=json

be : https://api.digitalriver.com/v1/shoppers/me/products/5438795700?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=fr_fr&format=json


Thank you very much for the hard work

**Comment by mihaiparvu** [comment]
@Zoralback good catch, PR #8 ought to fix this.
