### ISSUE TITLE
EVGA bot login issue

### ISSUE THREAD

**Issue by arbyyyyh** [Hari-Nagarajan/nvidia-bot#108]
I am running on linux and trying to use the evga bot and after completing the CAPTCHA and click login, I get an "ERROR: Please to contact web manager" on the webpage. I have filled out the EVGA_config file. I originally did not want to auto purchase and left my CC info out but added in hopes that might make a difference. Any advise?

**Comment by shiftstealth** [comment]
I'm getting the same thing now. As soon as the bot stopped running it let me in. Seems like they are preventing it.

**Comment by camborambo** [comment]
Same issue here. Looks like bot prevention.
