### ISSUE TITLE
Can't seem to get past 'Getting product IDs' anymore

### ISSUE THREAD

**Issue by stevenhay** [Hari-Nagarajan/nvidia-bot#109]
![image](https://user-images.githubusercontent.com/26744309/94071421-c3a90f80-fdeb-11ea-8ca7-0b96ca821237.png)

hangs on getting session token but I can access https://store.nvidia.com/store/nvidia/SessionToken on the selenium spawned browser just fine

**Comment by Gursheys** [comment]
NVIDIA changed stuff on their site, bot is temporarily broken for NVIDIA

**Comment by stevenhay** [comment]
Ah, I see, yeah it also seems like 'access_token' was changed to 'session_token'

**Comment by arbyyyyh** [comment]
So uhh, if it's working for me at the moment I should keep letting it crank?

**Comment by Gursheys** [comment]
> So uhh, if it's working for me at the moment I should keep letting it crank?

if its still running and you never restarted it, when it goes back in stock it won't work anyways

**Comment by tonienri** [comment]
I tried accessing directly: https://api.digitalriver.com/v1/shoppers/me/products?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=it_IT&format=json

It returns 403. API Key changed maybe?

**Comment by stevenhay** [comment]
Seems like it, I'm not sure how to find the API key so I'm also watching https://github.com/jef/nvidia-snatcher/issues/254

**Comment by Akzyra** [comment]
digital river outside access blocked, now nvidia api. `https://api-prod.nvidia.com/direct-sales-shop/DR/add-to-cart` needs a challange from the capcha. but not always an error if its missing.

Will probably change depending on how hard their server is getting hammered.

**Comment by SuperBigPeter** [comment]
That's unfortunate seeing as the 3090 drops in about 12 hours.

**Comment by Flight777** [comment]
New API looks like (for NL store): https://api-prod.nvidia.com/direct-sales-shop/DR/products/nl_nl/EUR/5438796700

**Comment by Hari-Nagarajan** [comment]
New API solved this.
