### ISSUE TITLE
Retry on exception?

### ISSUE THREAD

**Issue by mike9011** [Hari-Nagarajan/nvidia-bot#13]
Thanks for creating this tool! Great work, however i have an issue once in a while which makes the script stop making new requests. Is it possible that the script automatically retries after an error?
```

raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.digitalriver.com', port=443): Max retries exceeded with url: /v1/shoppers/me/products/5438796700/inventory-status?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=nl_nl (Caused by ResponseError('too many 429 error responses'))

```

Edit; it's a rate limit, maybe lowering the request frequency?

**Comment by Hari-Nagarajan** [comment]
Think this is done already.
