### ISSUE TITLE
Allow Amazon environment to crawl entire 3080 landing page and/or specific URL

### ISSUE THREAD

**Issue by NickAppleese** [Hari-Nagarajan/nvidia-bot#130]
Landing page:  https://www.amazon.com/stores/GeForce/RTX3080_GEFORCERTX30SERIES/page/6B204EA4-AAAC-4776-82B1-D7C3BD9DDC82

This could be an option for those who don't care which AIB they get.

**Comment by Hari-Nagarajan** [comment]
We can now search for a list of ASINS.
