### ISSUE TITLE
Use amazon multi-product add-to-cart URL / feature to check for stock / checkout?

### ISSUE THREAD

**Issue by gitgitcom** [Hari-Nagarajan/nvidia-bot#140]
eg 
https://www.amazon.com/gp/aws/cart/add.html?ASIN.1=B08HR7SV3M&Quantity.1=1&ASIN.3=B08HR3Y5GQ&Quantity.3=1&ASIN.4=B08HH5WF97&Quantity.4=1&ASIN.5=B08HHDP9DW&Quantity.5=1&Quantity.6=1&ASIN.7=B08HJS2JLJ&Quantity.7=1&ASIN.8=B08HJTH61J&Quantity.8=1

**Comment by Hari-Nagarajan** [comment]
Already being worked on: https://github.com/Hari-Nagarajan/nvidia-bot/pull/139
