### ISSUE TITLE
Nvidia only working for en_us locale? 2060S in stock but not adding to cart.

### ISSUE THREAD

**Issue by notpentadactyl** [Hari-Nagarajan/nvidia-bot#143]
Tested for `de_de` and `de_at`.

![2060s](https://user-images.githubusercontent.com/21175961/94306862-0269d180-ff74-11ea-827e-bd6cea1ef419.png)

https://api-prod.nvidia.com/direct-sales-shop/DR/products/de_de/EUR/5394902900 is telling me that it is in stock (also in stock if I go the nvidia store)

**Comment by notpentadactyl** [comment]
It seems to ONLY work for `en_us`.

**Comment by Hari-Nagarajan** [comment]
It looks like the problem is here:
https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/stores/nvidia.py#L20

Need to change
```
NVIDIA_STOCK_API = "https://api-prod.nvidia.com/direct-sales-shop/DR/products/{locale}/USD/{product_id}"
```
to 
```
NVIDIA_STOCK_API = "https://api-prod.nvidia.com/direct-sales-shop/DR/products/{locale}/{currency}/{product_id}"
```

And then use
```
        response = self.session.get(
            NVIDIA_STOCK_API.format(product_id=product_id, locale=self.locale, currency=get_currency_for_locale(locale=self.locale)),
            headers=DEFAULT_HEADERS,
        )
```

Need to implement a ```get_currency_for_locale(locale)``` function

**Comment by notpentadactyl** [comment]
quick test changing `USD` to `EUR` fixes it! 👍
