### ISSUE TITLE
nvidia store api change (again)?

### ISSUE THREAD

**Issue by notpentadactyl** [Hari-Nagarajan/nvidia-bot#147]
title

**Comment by Hari-Nagarajan** [comment]
Nvidia side errors right now

**Comment by snoopy-byte** [comment]
yeah your code was running great.... had it going for 5 hours or so.... something changed no?

**Comment by geekyed** [comment]
watching to see if the request changes from the front end

**Comment by Hari-Nagarajan** [comment]
@snoopy-byte Nvidia's apis are being unresponsive, this happens pretty often

**Comment by kirbdee** [comment]
it looks like it's still called on their site, so this might be an issue on their end vs and actual change

**Comment by snailQQ** [comment]
nvidia api dead.

**Comment by TackyBrad** [comment]
So now what?
