### ISSUE TITLE
Add max price field for Amazon 

### ISSUE THREAD

**Issue by astateofmind01** [Hari-Nagarajan/nvidia-bot#148]
Previous version there was the option to specify Max price on amazon, seems to be gone now (at least from config).

**Comment by SixTfour** [comment]
This. I think adding a check on subtotal would be sufficient enough. It would also potentially keep it from buying multiple GPUs in the same cart. Personally, I prefer that approach anyways since this project was made for people who actually just want a GPU and not for scalpers).

**Comment by Hari-Nagarajan** [comment]
Yeah it's just a bit complicated to do with the method we are using. It's on the to-do list though.

**Comment by astateofmind01** [comment]
It's a bit scary to use the amazon store right now, might snatch a scalper card at 3k :D

**Comment by myn** [comment]
If max price is to complex with the new process would limiting the purchase from specific merchants like only Amazon be easier to validate?

**Comment by Hari-Nagarajan** [comment]
It won't grab a scalper card, the add to cart url we are using only picks up cards from the primary seller on the product page. The 3rd party scalper listings won't add to cart this way.

**Comment by freejack** [comment]
> It won't grab a scalper card, the add to cart url we are using only picks up cards from the primary seller on the product page. The 3rd party scalper listings won't add to cart this way.

If that's the case I'll remove my pr.

**Comment by joseph-tobin** [comment]
How complicated is this to implement? Surely we just need to get the value of the price element before hitting checkout and compare it to something defined in a config file?
