### ISSUE TITLE
Add cache to gitignore

### ISSUE THREAD

**Issue by zuliwa** [Hari-Nagarajan/nvidia-bot#15]
I use the desktop app and it recognises all the cached files as changes, would it be possible to add them to the .gitignore file?

![image](https://user-images.githubusercontent.com/11893054/93717104-e3360300-fb73-11ea-9942-9257c9750841.png)

Also I don't know if this matters but your .gitignore file says /discord_config.json when the other config .json files don't have a slash

![image](https://user-images.githubusercontent.com/11893054/93717147-1ed0cd00-fb74-11ea-8001-cdc68c75b0eb.png)

**Comment by kissu** [comment]
Feel free to submit a PR and for the `.gitignore`, specifying the root path (`/`) or not is pretty much the same since the file itself (`.gitignore`) is at the root of the project. 😄
