### ISSUE TITLE
Add Associate Code field for evga store?

### ISSUE THREAD

**Issue by astateofmind01** [Hari-Nagarajan/nvidia-bot#154]
If possible can you add Associate Code field for checking out on evga store?

Thanks :)

**Comment by DakkJaniels** [comment]
Looks like this was removed under #106. Probably simple enough to add back in.

**Comment by DakkJaniels** [comment]
Question would be if it would easier for them to just ban you if you keep refreshing using your associate code?

**Comment by astateofmind01** [comment]
> Question would be if it would easier for them to just ban you if you keep refreshing using your associate code?

You don't, you only use the Associate Code when at check out. On the same page with selecting payment method (at least for regular items, not sure for the 30x0 ... 

Plus the associate code is not unique to a person, can be used by many.

Plus:: you are already logged in so your account is already recorded - would be easier to ban based on account.

**Comment by DakkJaniels** [comment]
Ah ok, the previous implementation had inserted the associate code in the URL, not at checkout, so implementing it like that would be more/new work.
