### ISSUE TITLE
Detect "Oops something went wrong" page on EVGA and go back to the card page

### ISSUE THREAD

**Issue by ChairGraveyard** [Hari-Nagarajan/nvidia-bot#155]
Sometimes EVGA's site will end up on the "Oops something went wrong" error page and the bot will just sit there refreshing that page.

The URL of the error page is: https://www.evga.com/Products/ErrorPage.htm?aspxerrorpath=/products/product.aspx

Would be nice if the bot detected this URL and navigated back to product.aspx?pn=<GPU_PN> before going into the refresh loop again.

**Comment by Hari-Nagarajan** [comment]
Thanks for the report, added to our list.

**Comment by ChairGraveyard** [comment]
Awesome, thanks!

**Comment by worst-mod-confirmed** [comment]
EVGA no longer sells directly except by individual code.
