### ISSUE TITLE
Amazon not auto buying

### ISSUE THREAD

**Issue by saltynut1** [Hari-Nagarajan/nvidia-bot#16]
I tested it on some starbursts and it clicked buy it now, but not the place your order button on the pop up it creates.

INFO: "2020-09-20 14:32:12,262 - Attempting to buy item for 12
INFO: "2020-09-20 14:32:12,664 - Clicking 'Buy Now'.
DEBUG: "2020-09-20 14:32:14,953 - Went to check out page.
Traceback (most recent call last):
  File "C:\Users\Zach\nvidia-bot\stores\amazon.py", line 95, in buy_now
    place_order = WebDriverWait(self.driver, 2).until(
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 225, in <module>
    cli.main()
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Zach\nvidia-bot\cli\cli.py", line 62, in amazon
    amzn_obj.run_item(item_url=amazon_item_url, price_limit=amazon_price_limit)
  File "C:\Users\Zach\nvidia-bot\stores\amazon.py", line 83, in run_item
    self.buy_now()
  File "C:\Users\Zach\nvidia-bot\stores\amazon.py", line 100, in buy_now
    place_order = WebDriverWait(self.driver, 2).until(
  File "C:\Users\Zach\.virtualenvs\nvidia-bot-AeXYW4nJ\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by saltynut1** [comment]
So sometimes when you press buy now it will open a new window, but other times it will go to a new page. I think the bot expects the new page but the window will break it. I can seem to force it to go to a new page if you refresh and click buy now very quickly, otherwise it opens the new window.

**Comment by Dinzy3** [comment]
Same issue here.  Buy it now opens a small window on top of current tab in the item I tried.

**Comment by ZenHikage** [comment]
Running into the same issue here as well.   Tried running a test with a cheap item a few times now, and keep getting that pop-up window as well.  Can't seem to bypass it in time for the script to halt.

**Comment by shiftstealth** [comment]
If you set your environment variables within pipenv shell it resolves this.

In your CLI put:

pipenv shell
set amazon_email=user@email.com
set amazon_password=supersecurepassword
set amazon_item_url=https://www.amazon.com/dp/B08HHDP9DW?
set amazon_price_limit=1000


Only change the variables for what you're looking for. 

Note: Some amazon links have characters that don't play nicely. So put them in bit.ly to fix that, and use the bit.ly link.

**Comment by ZenHikage** [comment]
Not sure if you're referring to the same issue that I'm encountering.

I'm able to run the script, and get to the product page just fine.  But once the item becomes available, instead of going to the next order screen, I'm getting a pop-up window asking to confirm the adding of the item to the cart.

From reading post from others, this seems to be happening randomly as well, and hasn't been able to be specifically replicated.  I believe Hari is tracking the issue as well, and may/have already fixed it.  I haven't tried a test purchase since earlier today.

**Comment by Hari-Nagarajan** [comment]
Try setting up 1 click on your amazon account

**Comment by shiftstealth** [comment]
Mmmmmm, I was getting the error that saltynut1 was having, and yes I could run the script too, but purchasing failed with his error.

Thanks Hari, That was my next suggestion. You need the buy it now button to be configured.

**Comment by ZenHikage** [comment]
I believe I already had the One-Click-Buy enabled, but I'll check again.  Thanks Hari.

**Comment by ZenHikage** [comment]
Hmm, looking back at Amazon, I'm running into a strange thing.  I can find the setting within the Account Settings to turn on 1-Click Buy, but the whole box that's supposed to be there, isn't.  Below is a screenshot of what I'm seeing when I use the "Buy Now" button on a product page.
![test](https://user-images.githubusercontent.com/71473388/93743176-666f4d00-fba4-11ea-8305-ce52a1b5ec8e.png)

It's almost like the 1-Click Buy option has been removed from my account.  To be honest, I've never used it before.  So I may be working of outdated info/features here.

**Comment by ZenHikage** [comment]
Looking at it further, the "Buy Now" button that I'm using may actually be the 1-Click Buy button.  It looks like Amazon may have changed how it works sometime in the past, and enabled it by default for everyone (and in this case changing the button name).  But, that being said, I still get the pop-up shown above, which of course prevents the script from purchasing the item.  

Thoughts?

**Comment by saltynut1** [comment]
Yeah there is no more 1-click toggle it only takes you to a default payment screen. I have the same screen that zenhikage has.

**Comment by Dinzy3** [comment]
What controls whether or not the buy it now button appears?  I tried to buy 3 dollar dish soap but the buy it not button was not there so it failed and threw a bluetooth error.  I found another one that wasn't in stock that did work.

**Comment by shiftstealth** [comment]
I'm getting the same thing as them now sadly.

Sucks :(

**Comment by johnconnor2020** [comment]
> I'm getting the same thing as them now sadly.
> 
> I also sometimes get an asurion popup trying to sell me a warranty which would prevent the automation from working as well.
> 
> Sucks :(

Can you post a screenshot?

**Comment by shiftstealth** [comment]
I receive this, attempting to sell me a warranty:
![image](https://user-images.githubusercontent.com/71617015/93933357-89f2de80-fcef-11ea-902c-98ef21ab33cb.png)

And then this 
![image](https://user-images.githubusercontent.com/71617015/93933387-94ad7380-fcef-11ea-908c-b487ab70e90a.png)

**Comment by camborambo** [comment]
> 
> 
> I receive this, attempting to sell me a warranty:
> ![image](https://user-images.githubusercontent.com/71617015/93933357-89f2de80-fcef-11ea-902c-98ef21ab33cb.png)
> 
> And then this
> ![image](https://user-images.githubusercontent.com/71617015/93933387-94ad7380-fcef-11ea-908c-b487ab70e90a.png)

I would blur out your personal details in that image. If you are concerned about it.

**Comment by shiftstealth** [comment]
I receive this attempting to sell me a warranty:

![image](https://user-images.githubusercontent.com/71617015/93933609-e524d100-fcef-11ea-920a-8af95d872347.png)

and then this prompt screen:

![image](https://user-images.githubusercontent.com/71617015/93933513-c9b9c600-fcef-11ea-8c41-da7a0ecb3baf.png)


@camborambo I removed it. If you could do the same I would appreciate it!

**Comment by shiftstealth** [comment]
@Hari-Nagarajan  are you able to remove the image above with my details? I forgot to remove them, and after I removed them they were quoted.

Thanks!

**Comment by Hari-Nagarajan** [comment]
> @Hari-Nagarajan  are you able to remove the image above with my details? I forgot to remove them, and after I removed them they were quoted.
> 
> 
> 
> Thanks!

Done!

**Comment by shiftstealth** [comment]
> > @Hari-Nagarajan  are you able to remove the image above with my details? I forgot to remove them, and after I removed them they were quoted.
> > Thanks!
> 
> Done!

Thanks so much, I appreciate it.

**Comment by camborambo** [comment]
@shiftstealth Sorry I saw this comment too late. Thanks for deleting that comment @Hari-Nagarajan

**Comment by Hari-Nagarajan** [comment]
This has been fixed.
