### ISSUE TITLE
EVGA oops! something broke error

### ISSUE THREAD

**Issue by drx19** [Hari-Nagarajan/nvidia-bot#173]
Hello, 

sometimes on evga website when the bot finds item and goes to add it to cart, chrome goes to the following page:
[https://www.evga.com/Products/ErrorPage.htm?aspxerrorpath=/products/ProductList.aspx](url)

![image](https://user-images.githubusercontent.com/71615615/94375874-affbf280-00e4-11eb-8117-e82b4b40a239.png)

I have noticed it is not the first time it has done it. it happens once a while when the bot finds item perhaps attemps select element and add it to cart. I confirmed the item never makes it to the cart by refreshing another tab that contains the cart. when the bot is restarted shortly after with the same parameters, the error does not replicate. it happens once while. this raises chance of failing when needed the most.

**Comment by WillsB3** [comment]
This should become less of an issue once #104 is resolved. Once that lands it should just automatically keep retrying until it was able to add the item to the cart without any further EVGA store specific code changes.
