### ISSUE TITLE
Nvidia - we shouldn't be notifying (sms, etc)  every request if the api for adding to cart fails.

### ISSUE THREAD

**Issue by geekyed** [Hari-Nagarajan/nvidia-bot#174]
I don't think pining and sending texts every 5 seconds when the api is down is a sensible thing to do. Only notify when the script has died or we have a card!

is_in_stock now has a try catch as follows:

`        except requests.exceptions.RequestException:
            self.notification_handler.send_notification(
                f"Got an unexpected reply from the server, API may be down, nothing we can do but try again"
            )
            return False`

this should just be a console.warn

**Comment by geekyed** [comment]
I suggest the following, if you dont fancy a text every 5 seconds.
`        except requests.exceptions.RequestException as e:
            log.error(f"Adding to cart url failed with the following: {e}")
            return False, ""`

**Comment by WillsB3** [comment]
@geekyed you happy for us to close this now https://github.com/Hari-Nagarajan/nvidia-bot/pull/181 is merged?
