### ISSUE TITLE
EVGA breaking at checkout ("select payment type" screen)

### ISSUE THREAD

**Issue by pauldofish** [Hari-Nagarajan/nvidia-bot#175]
Hey all,

EVGA --test is breaking during the checkout process. Seems like it's not correctly locating the Credit card selection button on the payment selection screen, which causes the bot to error out. I tried re-running a handful of times, so I don't think this is a fluke. See screenshot below. 

![image](https://user-images.githubusercontent.com/71990763/94377272-f9dcdc80-00d4-11eb-87ce-a4a4c52b7d9e.png)

**Comment by Sadge-spec** [comment]
Same issue here

**Comment by pauldofish** [comment]
A quick fix that seemed to work for me just now was to change the sleep timer from 1 to 5 on [this line in the evga.py script](https://github.com/Hari-Nagarajan/nvidia-bot/blob/cc5ab32abc12c9400750850595b9957f35d7ab8c/stores/evga.py#L169)
