### ISSUE TITLE
Amazon chrome window stuck

### ISSUE THREAD

**Issue by Illandren** [Hari-Nagarajan/nvidia-bot#188]
For some reason after trying amazon with --no-image option, now whenever I try to run it with image it continues to block images. Looking at the chrome settings in the chrome window that comes up by running amazon it says that the option is blocked by my administrator.

Anyone know how to fix that? Uninstalling and reinstalling selenium did not help.

**Comment by astateofmind01** [comment]
delete the .profile.amz directory in your folder. But that will delete all your cookies as well.

**Comment by Illandren** [comment]
This did it. Thanks.
