### ISSUE TITLE
[minor] Missing comma in telegram template

### ISSUE THREAD

**Issue by TerryFrench** [Hari-Nagarajan/nvidia-bot#19]
Missing comma at the end of the "BOT_TOKEN" line. 
That could make non-dev adoption a bit harder.

{
    "BOT_TOKEN" : "1234567890:abcdefghijklmnopqrstuvwxyz",
    "BOT_CHAT_ID" : "111222333"
}

**Comment by mihaiparvu** [comment]
It was fixed in https://github.com/Hari-Nagarajan/nvidia-bot/commit/9e73f289391b7984b4d0ca41fd13478df0626332. Update your sources :)
