### ISSUE TITLE
Amazon - bot adds wrong item

### ISSUE THREAD

**Issue by LiberatedPotato** [Hari-Nagarajan/nvidia-bot#190]
I want to start by saying I made my account today and I'm 100% brand new to GitHub. If anything I say can be fixed easily try to be understanding.

I got the bot up an running and managed to set up the configs but I cannot use the amazon command because the bot keeps trying to purchase a flash drive is there a fix? can I exempt the product somehow?

Many thanks people of github.

**Comment by Illandren** [comment]
You need to fix your amazon_config.json. You will need to open it in whatever text editor that you have. Notepad works if you have nothing better.

You need to modify the ASIN in this file. You will see a line that shows

`"asin_list": ["1654414018"]`

Yours will show an ASIN for a thumb drive. this one here is for a Python for beginners book. You can find the ASIN of the item you want to buy by navigating to it in your browser and looking at the URL. For Amazon the ASIN is always located after /dp/

For our example above the URL is https://www.amazon.com/Python-Beginners-Books-Programming-Workbook/dp/1654414018/

Please respond if you get stuck.

**Comment by LiberatedPotato** [comment]
I got it.
To up my chances of getting a card I need to find and add as many ASIN's as possible to the list? and if I do that I might risk purchasing multiple cards right?
Anyhow you've been a great help.

**Comment by Illandren** [comment]
Not entirely sure on that one. I've just been keeping to a single ASIN.

**Comment by astateofmind01** [comment]
> Not entirely sure on that one. I've just been keeping to a single ASIN.
> 
> Edit: I looked into it a little more, and yes, it would up your chances of getting a card but you could also buy multiple cards if 2 or more came in stock within the same window of time. I suppose you could always go back and cancel the cards that you don't want.

Not sure if it's possible to cancel only one item from the order. Maybe you can.

But anyway for now i think there is a capthca before placing the order so you can risk an edit it :D

**Comment by Hari-Nagarajan** [comment]
You can cancel a single item from an order for sure.
