### ISSUE TITLE
Amazon 

### ISSUE THREAD

**Issue by yukkerz** [Hari-Nagarajan/nvidia-bot#192]
Seems like a card went up under 3rd party seller but it was still an amazon seller and the bot didn't trigger. Not sure if we can set it to search 3rd party also with amazon or maybe buy any at a set price.

**Comment by Dinzy3** [comment]
Another user mentioned that all EVGA cards on Amazon were listed by Amazon LLC and that these do not show up in the add to cart screen.

**Comment by broncosmang** [comment]
it's missed a couple legitimate drops on amazon.  seems like the add to cart page isn't showing availability for an asin even when there is availability.  could be because amazon has tucked it away behind the 'see all buying options' when an asin becomes availabile on the rtx landing page?

**Comment by Dinzy3** [comment]
Could this issue be solved by updating the old Amazon bot with the captcha and error handling?

**Comment by Hari-Nagarajan** [comment]
I think theres some confusion on what I mean by "third party seller". 

This LG monitor (B08BCRYS6B) has a seller on the listing itself for $799. The amazon bot will purchase this. 
![image](https://user-images.githubusercontent.com/39167399/94826802-b1c00180-03d5-11eb-86a0-625d315b4722.png)

The NR200 (B08BFJHP26) here is available "from these sellers" which is a list of sellers who are not the primary seller on the listing. 
![image](https://user-images.githubusercontent.com/39167399/94826911-d1efc080-03d5-11eb-90d8-1cc65712d8a2.png)

The auto add to cart functionality we are using will only add items to the cart that in stock and sold by the primary seller on the listing. This piece of functionality is well tested so far, I've made multiple purchases for items sold by the primary seller the second the item is in stock. Some of these recent drops were added to the listing not under the main seller on the listing and the add to cart functionality missed them. Reverting to the old amazon bot (that refreshed a single item page) would not solve this, as the buy now button would not appear unless the primary seller on the listing has the item in stock.

**Comment by Dinzy3** [comment]
Makes sense.  I am about 51% sure I saw the buy it now button for the gigabyte cards yesterday but it was gone almost instantaneously.  I removed that item from my product list so the bot would not have caught it.  I guess since Amazon has sold so few cards, it's hard to collect any solid data to decide whether the primary seller/buy now strategy is problematic with RTX 30XX on Amazon.  The only cards they have had up were ones that I was not including in bots during the window of availability or scalped ones.

**Comment by nvidia-buyer** [comment]
I believe either it's a system issue, or they are not adding them as first party on purpose, but another sale went up today at 2 am and it was up for minutes (evga). My distill even caught a detail page with a "Buy now" button, and it didn't work in the end. 

For whatever reason, this method doesn't even detect them as being in stock. Could be Amazon showing up as a third party seller (which it does, maybe a caching issue, maybe intentionally), or Amazon intentionally preventing this method of working to deter bots. 

In the end Distill in a browser is working better, sadly.
