### ISSUE TITLE
Missing Product ID for CS_CZ locale (Czech republic)

### ISSUE THREAD

**Issue by AlisarDius** [Hari-Nagarajan/nvidia-bot#194]
Hello,

Locale for cs_cz (czech republic) doesn't have product ID set up. I'm living in Czechia so I think I have to use this locale.
Would it be possible to add that product ID for it?
 
![image](https://user-images.githubusercontent.com/45385960/94584185-98587180-027e-11eb-8a04-9f5715825067.png)

**Comment by AlisarDius** [comment]
is this the product ID? https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_gb/CZK/5438793800

![image](https://user-images.githubusercontent.com/45385960/94587695-3c441c00-0283-11eb-8cb0-0678431a1fbe.png)

**Comment by WillsB3** [comment]
Yep. I’ll add this in a bit. Could you get me the one for the 3090 from where you are as well please?

**Comment by AlisarDius** [comment]
here it is: Request URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_gb/CZK/5438793600,5438794000

for some reason it has 2 IDs in the API
![image](https://user-images.githubusercontent.com/45385960/94602402-1758a480-0295-11eb-9fa1-0204e64b99f6.png)

**Comment by WillsB3** [comment]
Thanks
