### ISSUE TITLE
Nvidia API may  be down

### ISSUE THREAD

**Issue by OnFire99** [Hari-Nagarajan/nvidia-bot#195]
In the Nvidia Store (de) the bot stops refresh an send the message via SMS: "got an unexpected reply from the server, API may be down". The issue is since 00:12 CET

**Comment by worst-mod-confirmed** [comment]
This issue was fixed with #181 . git pull and it will go away.

**Comment by OnFire99** [comment]
> This issue was fixed with #181 . git pull and it will go away.

Sorry, it doesn't work. The same issue but now without SMS, just message in cmd Window

**Comment by worst-mod-confirmed** [comment]
It doesnt stop refreshing, the API is down, the only way we know the API is down is by checking to see if that is actually the case. I misunderstood the issue as being you were getting SMS notifications about it which we indeed unintended, but the notifications about the API being down are intended.
