### ISSUE TITLE
Amazon.de suddenly forever "waiting for home page" Amazon.com works

### ISSUE THREAD

**Issue by FIocker** [Hari-Nagarajan/nvidia-bot#199]
Some change about the home page seems to be tripping the bot, maybe the prime-day related stuff?

**Comment by johnconnor2020** [comment]
Please post the error log from the command window and the error log from the txt file.

**Comment by johnconnor2020** [comment]
Are you getting stuck in the last page in the checkout menu before Buy now? I have same issue.

**Comment by johnconnor2020** [comment]
I already submitted a pull request, so it should be fixed soon.

**Comment by johnconnor2020** [comment]
Has been fixed.
