### ISSUE TITLE
Amazon bot crashing after the captcha update 

### ISSUE THREAD

**Issue by drx19** [Hari-Nagarajan/nvidia-bot#206]
Hello, the bot was running and checking item is in stock for about 2 hours until I received the crash message. 

![image](https://user-images.githubusercontent.com/71615615/94816654-1bd2a980-03ca-11eb-8058-eeba34d5f575.png)

wait_for_pages file is below
![amazon-wait_for_pages](https://user-images.githubusercontent.com/71615615/94816710-3147d380-03ca-11eb-820c-c74fc74de0c4.png)

**Comment by gylli251** [comment]
Same for me.

**Comment by Hari-Nagarajan** [comment]
Pull latest

**Comment by shroyhammer** [comment]
I've got fair game 6.0, same shit happening here, anyone has a fix yet?
I just want one GPU.  Just one.  Motherfuckers out there with carts full, frothing at the mouth like some kind of heroine junky, just knifing homies like us to feed their addiction.
It's a sick, sad world.
HAAAAALLLLLPPPP

**Comment by DakkJaniels** [comment]
@shroyhammer while I appreciate your enthusiasm, can you please stop spamming the issues log? Especially on closed issues.

**Comment by shroyhammer** [comment]
@DakkJaniels LOL **so sorry man**, yes I will stop.  Is this issue closed because we found a way to fix this or because we've given up?
My "spam" was literally a call for help on this issue that I have not found a resolution to yet.
Thanks compadre

**Comment by DakkJaniels** [comment]
is it crashing on captcha? That's what this issue is for.

If it's not solving captchas,  that's a different issue. As stated in #396 we use a module to do it, so if it can't solve them, it can't solve them. There are a few fixes to deal with captcha during checkout, but I don't think we have anything for captchas during stock check.

**Comment by shroyhammer** [comment]
@DakkJaniels Nah man, it's not crashing, but it gets stuck on captcha eventually.  I've watched it solve them when I log in, but after running a while it's always stuck there.  If I was to leave my set up for the day, whenever I come back it's always stuck on the screen above with the captcha on it 🤷‍♂️. 
I'm running two fair game "bots" with different asin numbers at the same IP address.
Not sure if that makes me a bigger target for Captchas or if its just normal to encounter unsolvable ones.
Thanks for your help man!

**Comment by shroyhammer** [comment]
@DakkJaniels 
![CAPTCHA error](https://user-images.githubusercontent.com/79087957/111831659-ebfe5c00-88ac-11eb-90b7-82a134de8549.png)
It just did it again.  Here's a screenie homie.
Please, it hurts!
