### ISSUE TITLE
German API (de-de) for Nvidia does not work

### ISSUE THREAD

**Issue by NeKoMuck** [Hari-Nagarajan/nvidia-bot#212]
INFO: "2020-10-02 16:13:27,889 - Initializing notification handlers
INFO: "2020-10-02 16:13:27,889 - Enabled Handlers: ['Audio', 'Discord']
? What GPU are you after?  3090
? What locale shall we use?  de_de
INFO: "2020-10-02 16:13:30,717 - Initializing notification handlers
INFO: "2020-10-02 16:13:30,733 - Enabled Handlers: ['Audio', 'Discord']
INFO: "2020-10-02 16:13:30,733 - We have 1 product IDs for NVIDIA GEFORCE RTX 3090
INFO: "2020-10-02 16:13:30,733 - Product IDs: ['5438761400']
INFO: "2020-10-02 16:13:30,733 - Stock Check 5438761400 at 5 second intervals.
INFO: "2020-10-02 16:22:32,371 - Got an unexpected reply from the server, API may be down, nothing we can do but try again
INFO: "2020-10-02 16:31:39,367 - Got an unexpected reply from the server, API may be down, nothing we can do but try again
INFO: "2020-10-02 16:40:46,173 - Got an unexpected reply from the server, API may be down, nothing we can do but try again
INFO: "2020-10-02 16:49:52,915 - Got an unexpected reply from the server, API may be down, nothing we can do but try again
INFO: "2020-10-02 16:58:59,658 - Got an unexpected reply from the server, API may be down, nothing we can do but try again
INFO: "2020-10-02 17:08:06,541 - Got an unexpected reply from the server, API may be down, nothing we can do but try again
INFO: "2020-10-02 17:17:13,296 - Got an unexpected reply from the server, API may be down, nothing we can do but try again

**Comment by spacesausage** [comment]
Same for others Nvidia stores right now. I tried with en_us (main one ) and few others and it returns the same message each time.

**Comment by johnconnor2020** [comment]
Check the discord for updates. The API is currently down, the bot however continues to check it.
