### ISSUE TITLE
Discord and 3080 Community in general is toxic

### ISSUE THREAD

**Issue by Dinzy3** [Hari-Nagarajan/nvidia-bot#215]
The discord is toxic.  I was trying to pass along some interesting observations I had on Ebay and I got attacked and then banned by some people who didn't even want to hear the story.  So what if I sold a 3090 on ebay once I got the 3080?  I bought it because I could after failing to get a 3080 for a week and finally scored the 3080 yesterday.  I tried to trade it via a post in the discord.  Nobody wanted it.   But even then, what am I supposed to do meet a stranger to swap 1600 bucks worth of goods?  Not really smart.  I was stuck with a 1590 dollar purchase so I chose to sell it on ebay because I wanted my money back safely.  I listed it for the average and explicitly stated I'd consider an offer for cost.  Which is 1590 + ebay and paypal fees + shipping. ~ 1900.  The person who bought it was ecstatic.  He had been trying to buy one anywhere for a week and was struggling on ebay because people were putting in ridiculous bids and buying cards they would pay for.  He was struggling to get one in his cart similar to retail.  My intention in coming to the chat and posting elsewhere was to try to inform people to stop doing that and just let that market stabilize.  People are posting that they are luring scalpers out and not showing up.  They are proud when they ruin an auction.  The difficulty in actually buying one on ebay is driving prices higher which is bad for everyone.  Instead of people hearing me out,  I was attacked and banned.  And I didn't get a chance to even explain.  It was really toxic and it is this same toxicity on ebay that is making it worse for everyone.  I prefer to be informed and I was hoping some there would like to as well.  Instead it is just hate and shaming people for how they back out of a split second decision.  At the end of the day, I made this guy happy that he got one.  He didn't care about the cost because he knows they are in short supply.  When all the people like him are gone or the supply meets demand, cards will be easier to get.  All that messing with ebay does is make it harder for the people like him to leave the market while supply is still short.  It makes it so many won't get cards until many drops in the future.  

It was fun while it lasted.  I got what I wanted after roughly 15 days of hell and I got rid of my card to someone who appreciated it and shared some back and forth email about it.  But I am some awful piece of trash that needed to be harassed and banned.  Awesome.

**Comment by worst-mod-confirmed** [comment]
Cool story, thanks for sharing.

**Comment by Das-Morgenstern** [comment]
God you are such a cock sucker @worst-mod-confirmed

**Comment by Das-Morgenstern** [comment]
> The discord is toxic.  I was trying to pass along some interesting observations I had on Ebay and I got attacked and then banned by some people who didn't even want to hear the story.  So what if I sold a 3090 on ebay once I got the 3080?  I bought it because I could after failing to get a 3080 for a week and finally scored the 3080 yesterday.  I tried to trade it via a post in the discord.  Nobody wanted it.   But even then, what am I supposed to do meet a stranger to swap 1600 bucks worth of goods?  Not really smart.  I was stuck with a 1590 dollar purchase so I chose to sell it on ebay because I wanted my money back safely.  I listed it for the average and explicitly stated I'd consider an offer for cost.  Which is 1590 + ebay and paypal fees + shipping. ~ 1900.  The person who bought it was ecstatic.  He had been trying to buy one anywhere for a week and was struggling on ebay because people were putting in ridiculous bids and buying cards they would pay for.  He was struggling to get one in his cart similar to retail.  My intention in coming to the chat and posting elsewhere was to try to inform people to stop doing that and just let that market stabilize.  People are posting that they are luring scalpers out and not showing up.  They are proud when they ruin an auction.  The difficulty in actually buying one on ebay is driving prices higher which is bad for everyone.  Instead of people hearing me out,  I was attacked and banned.  And I didn't get a chance to even explain.  It was really toxic and it is this same toxicity on ebay that is making it worse for everyone.  I prefer to be informed and I was hoping some there would like to as well.  Instead it is just hate and shaming people for how they back out of a split second decision.  At the end of the day, I made this guy happy that he got one.  He didn't care about the cost because he knows they are in short supply.  When all the people like him are gone or the supply meets demand, cards will be easier to get.  All that messing with ebay does is make it harder for the people like him to leave the market while supply is still short.  It makes it so many won't get cards until many drops in the future.  
> 
> 
> 
> It was fun while it lasted.  I got what I wanted after roughly 15 days of hell and I got rid of my card to someone who appreciated it and shared some back and forth email about it.  But I am some awful piece of trash that needed to be harassed and banned.  Awesome.  
> 
> 
> 
>    

@Hari-Nagarajan can you please take control of your server. Analyze what is going on because though I truthfully did not portray my idea in a totally clear sense, I still messed up. But this dude clearly did nothing wrong and wasn't given a warning. Please dude. It's turning toxic quick.
