### ISSUE TITLE
Amazon ordering bug

### ISSUE THREAD

**Issue by Niizan** [Hari-Nagarajan/nvidia-bot#218]
when i try to run the amazon script, it will always give me this error: 

ERROR: "2020-10-03 18:26:27,889 - An error happened, please submit a bug report including a screenshot of the page the selenium browser is on. There may be a file saved at: amazon-wait_for_pages.png

![image](https://user-images.githubusercontent.com/71811197/95003952-a671ff00-05aa-11eb-9ef8-f6252e50272a.png)

**Comment by WillsB3** [comment]
Is that Spanish? We don't have page title strings for that language yet. Change your language on Amazon to en-us or en-uk and it should work

**Comment by Niizan** [comment]
it did, thanks a lot
