### ISSUE TITLE
tkinter did not import successfully. Please check your setup.

### ISSUE THREAD

**Issue by jdkennedy45** [Hari-Nagarajan/nvidia-bot#22]
> (nvidia-bot2-N-x_5dcQ) C:\Users\Jake\PycharmProjects\nvidia-bot2>python app.py
> tkinter did not import successfully. Please check your setup.

I setup everything just like instructed but keep getting this error when running app.py?

**Comment by gregoiredelzongle** [comment]
you have to type "python app.py nvidia"

**Comment by jdkennedy45** [comment]
> you have to type "python app.py nvidia" or "python app.py amazon"

same result on my end

**Comment by gregoiredelzongle** [comment]
`pipenv install ` gives you no luck ?

**Comment by jdkennedy45** [comment]
> (nvidia-bot2-N-x_5dcQ) C:\Users\Jake\PycharmProjects\nvidia-bot2>pipenv install
> Installing dependencies from Pipfile.lock (52c0b5)…
>   ================================ 0/0 - 00:00:00


Just this so it has all the dependencies, I believe. I just don't have tkinter for some reason?

**Comment by gregoiredelzongle** [comment]
yeah maybe you should just do `pip install tkinter`

**Comment by jdkennedy45** [comment]
> (nvidia-bot2-N-x_5dcQ) C:\Users\Jake\PycharmProjects\nvidia-bot2>pipenv install tkinter
> Installing tkinter…
> Error:  An error occurred while installing tkinter!
> Error text:
> ERROR: Could not find a version that satisfies the requirement tkinter (from -r c:\users\jake\appdata\local\temp\pipenv-v53e8fbv-requirements\pipenv-xd17mji5-requirement.txt (line 1)) (from ve
> rsions: none)
> ERROR: No matching distribution found for tkinter (from -r c:\users\jake\appdata\local\temp\pipenv-v53e8fbv-requirements\pipenv-xd17mji5-requirement.txt (line 1))
> 
> Installation Failed


It couldn't find anything named tkinter, evidently.

**Comment by jdkennedy45** [comment]
Yep, looks like I had a corrupted python installation.
