### ISSUE TITLE
Amazon.de/Amazon.fr/Amazon.es Checkout

### ISSUE THREAD

**Issue by SuperSamy** [Hari-Nagarajan/nvidia-bot#236]
I'm also trying on Amazon.de, Amazon.es and Amazon.fr, but the screen to select the address and payment method comes out, how can I go directly to the checkout page (Submit order)?
![amz de](https://user-images.githubusercontent.com/48161104/95225045-a583dc00-07fb-11eb-95c5-046ea1280076.png)

**Comment by astateofmind01** [comment]
Add your address in your account and set it as default?

**Comment by SuperSamy** [comment]
> Add your address in your account and set it as default?

Yes, now it works perfectly, but it doesn't complete the purchase, it gets stuck at the last step (FR and ES only)
