### ISSUE TITLE
Amazon.ES / FR Checkout doesn't work

### ISSUE THREAD

**Issue by SuperSamy** [Hari-Nagarajan/nvidia-bot#241]
At the checkout stage, both Amazon.FR and Amazon.ES don't click "Submit order", would anyone be able to fix it? Thank you.
The "CHECKOUT_TITLES" has already been entered, but it doesn't work anyway.
@WillsB3 

![8s3E5o2](https://user-images.githubusercontent.com/48161104/95331679-a0319a80-08aa-11eb-9910-a8505fe6ad02.png)
![r72lwwO](https://user-images.githubusercontent.com/48161104/95331685-a162c780-08aa-11eb-9950-ffdd6e67dac8.png)

**Comment by SuperSamy** [comment]
UP

**Comment by SuperSamy** [comment]
UP

**Comment by Hari-Nagarajan** [comment]
Can you post the page titles for these?

**Comment by SuperSamy** [comment]
CHECKOUT_TITLES

ES: 
"Confirmar pedido -  Compra Amazon.es"

FR: 
"Passez votre commande - Processus de paiement Amazon.fr"

**Comment by SuperSamy** [comment]
@Hari-Nagarajan 
![image](https://user-images.githubusercontent.com/48161104/95579088-43aeb680-0a35-11eb-84b0-04fc90459532.png)

**Comment by Walhalla360** [comment]
here both work with my changes here: #268
