### ISSUE TITLE
Not Able to Use Amazon.com Normally After Running the Amazon Bot

### ISSUE THREAD

**Issue by Das-Morgenstern** [Hari-Nagarajan/nvidia-bot#245]
I've found that Amazon will now request very frequently for me to complete a Captcha and won't let me read reviews or leave questions on items other than the GPU's that I've added to the config file. Wanted to know if others are experiencing this problem and if it can be resolved because it's pretty annoying.

<img width="1440" alt="Screen Shot 2020-10-08 at 9 49 50 AM" src="https://user-images.githubusercontent.com/72041255/95467634-b3e10d80-094b-11eb-9ccf-9345fd19daa6.png">

**Comment by astateofmind01** [comment]
Clear cache and cookies.

**Comment by Das-Morgenstern** [comment]
Gotcha

**Comment by richee75** [comment]
Getting the same thing.  Cleared cache and cookies and still getting the error.
