### ISSUE TITLE
Autobuy not functional

### ISSUE THREAD

**Issue by czwawzh** [Hari-Nagarajan/nvidia-bot#25]
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 49 (char 50)
I keep getting this error, why?

**Comment by evanotero** [comment]
Delete the comments (denoted with `#`. Example: `# BLAH BLAH BLAH BLAH`) in the JSON file.

**Comment by czwawzh** [comment]
> Delete the comments (denoted with `#`. Example: `# BLAH BLAH BLAH BLAH`) in the JSON file.

That and making sure "true" was lower case solved the issue. Thanks!

**Comment by evanotero** [comment]
Created a pull request to add that instruction to the README: https://github.com/Hari-Nagarajan/nvidia-bot/pull/26

Also, if you ever want to make sure you have valid JSON, you can copy and paste the file contents into this website: https://jsonlint.com/

**Comment by evanotero** [comment]
This can be closed now.
