### ISSUE TITLE
Amazon error stuck on the main page

### ISSUE THREAD

**Issue by Finnedsgang** [Hari-Nagarajan/nvidia-bot#255]
Hi I have an error using the bot for amazon.it, the bot correctly starts the browser page on amazon.it, then it stops when logging in. I tried to log in manually but the same problem. It stays there and then shows this message 
 INFO Waiting for the home page.
 ERROR An error happened, please submit a bug report including a screenshot of the page the selenium browser is on. There may be a file saved at amazon-wait_for_pages.png
![amazon-wait_for_pages](https://user-images.githubusercontent.com/69695968/96456351-aadf1e80-121e-11eb-9bcc-1060deb7d672.png)

**Comment by Finnedsgang** [comment]
this is the image produced when logged in (manually)
![amazon-wait_for_pages](https://user-images.githubusercontent.com/69695968/96456561-ed086000-121e-11eb-88bc-7b9986be8eaa.png)

**Comment by perfectra1n** [comment]
Can you please post the entire log output, before the error happened, and the entire error?

**Comment by Finnedsgang** [comment]
> Can you please post the entire log output, before the error happened, and the entire error?

Hi, thanks for the reply. 
This is everything i can see. 
After a minute after the error the browser page close
![amazon](https://user-images.githubusercontent.com/69695968/96498892-f4466280-124c-11eb-8244-a444a3ffb3e9.JPG)

**Comment by Finnedsgang** [comment]
Any ideas of why i've this problem? the nvidia command works great (with no luck unfortunately, but works)

**Comment by Walhalla360** [comment]
Hi guys, Hari ist stuck on the main page, because it is missing the page titles for the Italian Amazon store at the moment. I added them here: #268

**Comment by worst-mod-confirmed** [comment]
Proposed fix was merged, reopen this issue if it is not resolved.
