### ISSUE TITLE
No Config File found 

### ISSUE THREAD

**Issue by Suuhhlly** [Hari-Nagarajan/nvidia-bot#256]
DEBUG: "2020-10-19 12:44:09,910 - Loading KWallet
DEBUG: "2020-10-19 12:44:09,910 - Loading SecretService
DEBUG: "2020-10-19 12:44:09,911 - Loading Windows
DEBUG: "2020-10-19 12:44:09,919 - Loading chainer
DEBUG: "2020-10-19 12:44:09,920 - Loading macOS
INFO: "2020-10-19 12:44:09,931 - Initializing Apprise handler
DEBUG: "2020-10-19 12:44:09,933 - No Apprise config found.
INFO: "2020-10-19 12:44:09,933 - Initializing other notification handlers
DEBUG: "2020-10-19 12:44:09,934 - Initializing local audio handler
DEBUG: "2020-10-19 12:44:09,934 - Initializing twilio handler
DEBUG: "2020-10-19 12:44:09,934 - No Twilio creds found.
DEBUG: "2020-10-19 12:44:09,934 - Initializing discord handler
DEBUG: "2020-10-19 12:44:09,934 - No Discord creds found.
DEBUG: "2020-10-19 12:44:09,934 - Initializing join handler
DEBUG: "2020-10-19 12:44:09,934 - No join config found.
DEBUG: "2020-10-19 12:44:09,934 - Initializing telegram handler
DEBUG: "2020-10-19 12:44:09,934 - No Telegram config found.
DEBUG: "2020-10-19 12:44:09,934 - Initializing slack handler
DEBUG: "2020-10-19 12:44:09,935 - No Slack creds found.
INFO: "2020-10-19 12:44:09,935 - Enabled Handlers: ['Audio']
DEBUG: "2020-10-19 12:44:10,506 - POST http://127.0.0.1:55877/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions": {"excludeSwitches": ["enable-automation"], "useAutomationExtension": false, "prefs": {"profile.managed_default_content_settings.images": 0}, "extensions": [], "args": ["user-data-dir=.profile-amz"]}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions": {"excludeSwitches": ["enable-automation"], "useAutomationExtension": false, "prefs": {"profile.managed_default_content_settings.images": 0}, "extensions": [], "args": ["user-data-dir=.profile-amz"]}}}
DEBUG: "2020-10-19 12:44:10,506 - Starting new HTTP connection (1): 127.0.0.1:55877
DEBUG: "2020-10-19 12:44:13,106 - http://127.0.0.1:55877 "POST /session HTTP/1.1" 200 664
DEBUG: "2020-10-19 12:44:13,106 - Finished Request
ERROR: "2020-10-19 12:44:13,106 - No config file found, see here on how to fix this: https://github.com/Hari-Nagarajan/nvidia-bot#amazon

I've redownloaded and reinstalled everything and still have this error. Any pointers would be great :)

**Comment by Suuhhlly** [comment]
Also from cmd output

DevTools listening on ws://127.0.0.1:55883/devtools/browser/11360305-8842-4612-a4a2-feef172a5e7c
[9168:16268:1019/124411.971:ERROR:CONSOLE(1)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-1+GSDjMMklBjZY0QiWq+tGupCvajw4Xbn46ect2mZgM=' 'sha256-2mX1M62Fd0u8q0dQY2mRsK5S1NS9jJuQAvyE8tD0dkQ=' 'sha256-EtIKSV82ixJHE3AzqhoiVbUGKG+Kd8XS0fFToow29o0=' 'sha256-QSyFltV9X3gkyBrg+SMfKvZNXmqPQc6K4B6OYhTuXmw=' 'sha256-ANdtIo91Yk/zh1YKZ+IXKP1pb00awOjEFMAUld02F6A=' 'sha256-CbH+xPsBKQxVw5d9blISLDeuMSe1M+dJ4xfArFynIfw=' 'sha256-lA+EURA/fC0TZq1ATYZvxIQHBc9iTAaBcI+dFMmTn9I=' 'sha256-ezOZE3GsFiiFM39LE8bQs5vdJyeJAqh3r+5jHc7863I='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
", source: chrome-search://local-ntp/local-ntp.html (1)

**Comment by perfectra1n** [comment]
Have you already set up your `amazon_config.json`? Or is it still in a template form at `amazon_config.template_json`?

**Comment by Suuhhlly** [comment]
Yep, looks like this:

{
  "username": “foo”,
  "password": “bar”,
  "asin_list": ["B08J6F174Z"],
  "amazon_website": "amazon.com”
}

**Comment by rekirk** [comment]
I'm having the same problem - any updates?

**Comment by worst-mod-confirmed** [comment]
This isn't a code issue, something is incorrect with your config file name.
