### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by wazerstar** [Hari-Nagarajan/nvidia-bot#260]
He contacted me after he banned me or had his friend ban me? for no reason.

His first message to me he instantly deleted contacting me to say, uhh you tried sneak in again, and kept writing nonesense where he acted like a kid, 

https://i.imgur.com/Fps3FEY.png

Apparently he did it again, he told another mod to ban me, again I did nothing

@Hari-Nagarajan 

@johnconnor2020

**Comment by johnconnor2020** [comment]
You are an idiot.
