### ISSUE TITLE
Nvidia not logging in

### ISSUE THREAD

**Issue by R1fast** [Hari-Nagarajan/nvidia-bot#27]
2060s en_us as test
Nvidia account fully configd with address, etc
creds in autobuy_config.json triple checked
script successfully adds 2060s and Rainbow 6 Siege to cart and sends discord notif

However, doesn't login....

![no_login](https://user-images.githubusercontent.com/28174023/93732223-45e3ca80-fb85-11ea-979c-246258b8a976.PNG)

Troubleshooting:

1. multiple attempts in cmd and pshell
2. cleared IE and Google cookies/cache, confirmed Google is default browser
3. reboot and retry
4. Nvidia creds do not show in login box in the browser window that opens
5. manually copy and paste of UN/PW from autobuy_config.json to cart login box does work

**Comment by evanotero** [comment]
Can you provide some more details:
1. Is the form below your cart showing an error?
2. Are your credentials not showing up in that form?
3. Have you tried logging in manually by copying and pasting the credentials you entered in the JSON file?
4. Did you remove `template_` when you copied the `autobuy_config.template_json`?

**Comment by R1fast** [comment]
Thanks @evanotero 

1. No error below cart (added snip below)
2. Creds are not showing up on the browser window that opens
3. Yes, have copied UN/PW from autobuy_config.json and they do work
4. Yes - file name = autobuy_config.json
![1](https://user-images.githubusercontent.com/28174023/93732664-2ea5dc80-fb87-11ea-85bd-9a87ffbbecd5.PNG)

**Comment by gitgitcom** [comment]
It looks like you have a space at the end of file name, try removing

**Comment by R1fast** [comment]
@gitgitcom thanks
 - yeah not sure why that snip looks like that but confirmed no space.  I reuploaded the snip for reference.

**Comment by R1fast** [comment]
Update:  I cleared Chrome cache and then logged into NV store, then closed Chrome again before doing anything else and then ran the bot and it worked - logged in ready to pay.  Thinking this was a local client issue and can close for now - user error.   Will add to troubleshooting section in case any others run into the login issue!
