### ISSUE TITLE
Bot trying to add to cart when product is unavailable. 

### ISSUE THREAD

**Issue by jabramsja** [Hari-Nagarajan/nvidia-bot#288]
Bot tries to add the unavailable item to cart and beeps. ASIN B0815Y8J9N

**Comment by DakkJaniels** [comment]
I am not seeing this error when I use this ASIN. Please post your error log.

**Comment by jabramsja** [comment]
There is no error message. It may just be that particular ASIN.
The page says "Adding to shopping cart". Below that it says the items are currently unavailable, but has a "continue" button. The bot clicks on the continue button and chimes. The bash says that it found the item was in stock even though it was not.

**Comment by DakkJaniels** [comment]
This is what I see: 
![image](https://user-images.githubusercontent.com/6080734/99140534-bd2b5d00-2610-11eb-9753-7a7eef9f5d5b.png)
What did the page look like when this happened?

**Comment by jabramsja** [comment]
Yes, that's the page that comes up. The bot then clicks the continue button, chimes, notifies that it is trying to add to cart, and goes to this page:
https://www.amazon.com/DANIPEW-Sand-Man-Cotton-Performance-T-Shirt/dp/B0815Y8J9N/ref=cm_cr_arp_d_product_top?ie=UTF8.

**Comment by DakkJaniels** [comment]
Are you running the code in the main branch? What ASINs are you using?

**Comment by jabramsja** [comment]
Looks like I was doing it wrong. Thank you very much for the help!
