### ISSUE TITLE
Discord notifications not sending

### ISSUE THREAD

**Issue by Pwnbeard** [Hari-Nagarajan/nvidia-bot#291]
When using apprise_config.json:

Notifications are pushed when test-notifications 
`python app.py test-notifications` 
is used as well as when apprise push notification
 `apprise -vv -t "Test Message Title" -b "Test Message Body" discord://{WebhookID}/{WebhookToken}` 
is used.

However, when running the application normally for Bestbuy with the following command and test sku known to be in stock
`python app.py bestbuy --sku 6405190`
No notification was pushed through discord.

Confirmed that the information is being pushed to apprise via message_sender queue in notification class.

**Comment by chaser13670** [comment]
I can confirm the same issue on my end. In my case I have my apprise_config.json setup with twilio. It successfully pushes notifications to my phone when using test-notifications, or when running amazon. When I use bestbuy no notification was pushed when starting i.e. python app.py bestbuy --sku 6430161. It also does not send any notifications when successfully pushing a dummy sku/item in stock through bestbuy to add to cart.

**Comment by DakkJaniels** [comment]
looks like it might be because program ends before it finishes queue. I'll make a PR to fix, just add a short sleep after the notification before the program ends.
