### ISSUE TITLE
version of chrome driver supports only chrome version 87

### ISSUE THREAD

**Issue by Randle-Lanre** [Hari-Nagarajan/nvidia-bot#296]
ERROR Message: session not created: This version of ChromeDriver only supports Chrome version 85, 
when running the command ``python app.py amazon --test``

**Comment by teatime** [comment]
You can change the  version requirement in "Pipfile", look for the line chromedriver-py = "==85" and change it to whatever version of chrome you have e.g. chromedriver-py = "==87.0.4280.20"
Then run "pipenv install" to install the new version

**Comment by manwith33** [comment]
I tried teatime's suggestion to change the requirement in Pipfile and run "pipfile install" but I get this error:  "CRITICAL:pipenv.patched.notpip._internal.index.package_finder:Could not find a version that satisfies the requirement chromedriver-py==87.0.4280.66"

**Comment by NicSenn** [comment]
> I tried teatime's suggestion to change the requirement in Pipfile and run "pipfile install" but I get this error: "CRITICAL:pipenv.patched.notpip._internal.index.package_finder:Could not find a version that satisfies the requirement chromedriver-py==87.0.4280.66"

change to chromedriver-py==87.0.4280.20" (20 on the end!)
