### ISSUE TITLE
Amazon.com Sorry something went wrong on our end message

### ISSUE THREAD

**Issue by TheCranky** [Hari-Nagarajan/nvidia-bot#312]
After running the script for about half an hour Amazon now displays an error message when the page refreshes. The issue seems to be related to either the session or user agent. If it is the latter, a user agent spoof rotation script combined with a browser reloader might be able to solve this problem.

**Comment by polleymister** [comment]
In your amazon_config.json file, is your url set to amazon.com? If so you need to switch it to smile.amazon.com.

**Comment by TheCranky** [comment]
I changed it and so far no problems. I did not think it mattered if I switched it to normal amazon.com after the latest update, but now I know it does. Thanks!

**Comment by polleymister** [comment]
If you haven't already, make sure you pick a charity on smile.amazon.com as I'm sure the bot won't know what to do when the website pops something up right when an item's added to the cart.
