### ISSUE TITLE
Wont buy Best buy Item

### ISSUE THREAD

**Issue by TheBlackGreatWhite1991** [Hari-Nagarajan/nvidia-bot#319]
Once its in stock INFO Item state is: ADD_TO_CART
 INFO Item 6430161 is in stock! then it just stops, why isn't it purchasing???????? using python 3.8

**Comment by TheBlackGreatWhite1991** [comment]
how do i enter purchase info for best buy? had 3 browsers open and logged in and the bot will say its in and then stop. no fill out no purchase just stops

**Comment by DakkJaniels** [comment]
This is not an issue, the bot clearly says it does not autobuy for Best Buy
