### ISSUE TITLE
When using Autobuy chrome immediately closes after launch.

### ISSUE THREAD

**Issue by Kneely23** [Hari-Nagarajan/nvidia-bot#32]
Using the bot without an autobuy config will open the chrome browser just fine and add a 2060s into a cart on the Nvidia website when testing. When having an autobuy config (without comments), thereby enabling autobuy, the bot will detect that the 2060s is in stock, open a chrome window, and then immediately close it. The bot then continues on a loop of saying that the 2060s is not in stock even though it is.

I am using the latest official version of chrome. I have tried reinstalling chrome on this windows machine and attempting to use the bot on a different mac machine with the same results. It has to be something to do with the implementation of opening chrome between autobuy being enabled and not. 

Here is a screenshot of command prompt: https://cdn.discordapp.com/attachments/756730877785931935/757484444352380948/qb0TUzR.png

Edit: Problem was fixed with latest release.

**Comment by kkreipe** [comment]
Remove the # lines and make sure you have an account on the nvidia store page, not their main nvidia website. those were my issues and how to resolve it.
