### ISSUE TITLE
Amazon websites display error when trying to add products to basket

### ISSUE THREAD

**Issue by SirDystic** [Hari-Nagarajan/nvidia-bot#320]
amazon scripts no longer seem to add products to basket properly. You can get round this on the amazon UK and DE sites by using smile.amazon.co.uk and smile.amazon.de for some reason but these equivalents don't exist on most amazon sites. Please could this be fixed. Its a very useful tool to try and get a GPU / Console. Thanks.

**Comment by DakkJaniels** [comment]
I don't understand what you mean, can you please provide screenshots or error messages from terminal/console?

**Comment by SirDystic** [comment]
So here is an example of the error. I get same from amazon.de amazon.co.uk or amazon.fr

![20201122_221118](https://user-images.githubusercontent.com/74874762/99918624-28abb380-2d10-11eb-9bfe-0f64ff66c138.jpg)
![20201122_221209](https://user-images.githubusercontent.com/74874762/99918625-2b0e0d80-2d10-11eb-9f73-b532e067df29.jpg)

but if i goto smile.amazon.co.uk or smile.amazon.de (and sign up for a charity) it works fine.

**Comment by worst-mod-confirmed** [comment]
You are using an old version that will no longer work. Amazon has some kind of flagging per ASIN that will cause that add.html page to return an error if any ASIN in the search list is flagged. Because of this, use of this page was removed in favor of single ASIN checking where the error didn't occur.

**Comment by SirDystic** [comment]
I only pulled it about a week ago so it's not very old!

So newer version still allows multiple ASINs but checks them individually?

**Comment by worst-mod-confirmed** [comment]
Week is a long time when amazon is making backend changes that we have to work around. Yes, current version looks at all the ASINs defined in the config one at a time.

**Comment by DakkJaniels** [comment]
User was using out of date program - issue closed
