### ISSUE TITLE
Need localization help!

### ISSUE THREAD

**Issue by Hari-Nagarajan** [Hari-Nagarajan/nvidia-bot#34]
We have some logic in Selenium for the login workflow and the final bits of the checkout workflow where we check the page title to ensure we are on the right page. These page titles vary based on localization. I need your help to get the page titles for each localization.

https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/stores/nvidia.py#L72-L143

```
    "fr_be": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "es_es": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "fr_fr": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "it_it": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "nl_nl": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "sv_se": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "de_de": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "de_at": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    },
    "en_gb": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Online Store - Checkout",
        'verify_order': "NVIDIA Online Store - Verify Order",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Online Store - Order Completed"
    }
```

**Comment by zuliwa** [comment]
```
"de_de": {
        'signed_in_help': "NVIDIA Online-Shop - Hilfe",
         'checkout': "NVIDIA Online-Shop - einkaufswagen",
         'verify_order': "NVIDIA Online-Shop - bestellung überprüfen und bestätigen",
    },
```
Couldn't get the rest as I couldn't provoke them yet

**Comment by gregoiredelzongle** [comment]
"fr_fr": {
        'signed_in_help': "NVIDIA Online Store - Help",
        'checkout': "NVIDIA Boutique en ligne - panier et informations de facturation",
        'verify_order': "NVIDIA Boutique en ligne - vérification de commande",
        'address_validation': "NVIDIA Online Store - Address Validation Suggestion Page",
        'order_completed': "NVIDIA Boutique en ligne - confirmation de commande"
    },

**Comment by notpentadactyl** [comment]
> 
> 
> ```
> "de_de": {
>         'signed_in_help': "NVIDIA Online-Shop - Hilfe",
>          'checkout': "NVIDIA Online-Shop - einkaufswagen",
>          'verify_order': "NVIDIA Online-Shop - bestellung überprüfen und bestätigen",
>     },
> ```
> 
> Couldn't get the rest as I couldn't provoke them yet
```
 "de_de": {
        'signed_in_help': "NVIDIA Online-Shop - Hilfe",
        'checkout': "NVIDIA Online Store - einkaufswagen",
        'verify_order': "NVIDIA Online-Shop - bestellung überprüfen und bestätigen",
        'address_validation': "NVIDIA Online-Shop - Adressüberprüfung Vorschlagsseite",
    },
```
No idea how we get the title for ` 'order_completed'`, but do we even need to check that? @Hari-Nagarajan

**Comment by zuliwa** [comment]
> > ```
> > "de_de": {
> >         'signed_in_help': "NVIDIA Online-Shop - Hilfe",
> >          'checkout': "NVIDIA Online-Shop - einkaufswagen",
> >          'verify_order': "NVIDIA Online-Shop - bestellung überprüfen und bestätigen",
> >     },
> > ```
> > 
> > 
> > Couldn't get the rest as I couldn't provoke them yet
> 
> ```
>  "de_de": {
>         'signed_in_help': "NVIDIA Online-Shop - Hilfe",
>         'checkout': "NVIDIA Online Store - einkaufswagen",
>         'verify_order': "NVIDIA Online-Shop - bestellung überprüfen und bestätigen",
>         'address_validation': "NVIDIA Online-Shop - Adressüberprüfung Vorschlagsseite",
>     },
> ```
> 
> No idea how we get the title for ` 'order_completed'`, but do we even need to check that? @Hari-Nagarajan

Looking at the flowchart we most likely only need this for the screenshot feature

**Comment by EmilLassen** [comment]
> ```
> “da_dk”: {
>         'signed_in_help': "NVIDIA Online-butik - Hjælp",
>         'checkout': "NVIDIA Online-butik - Udcheckning”,
>     }
> ```
Could not find the rest, as there are no items that you currently can purchase on the danish site.

**Comment by gregoiredelzongle** [comment]
sorry, the correct sentence for the help section for fr_fr (probably fr_be too) is 
"signed_in_help": "NVIDIA Boutique en ligne - Aide",

**Comment by notpentadactyl** [comment]
@Hari-Nagarajan `de_at` should be the same as `de_de`, German is German. (not tested)

**Comment by Hari-Nagarajan** [comment]
> @Hari-Nagarajan `de_at` should be the same as `de_de`, German is German. (not tested)

Apparently they are different locales on nvidia's api

**Comment by notpentadactyl** [comment]
@Hari-Nagarajan they are different stores, one is Germany, one is Austria, but the "language" should be the same, meaning the translation for `de_de` and `de_at` should be the same. If that helps.

**Comment by Hari-Nagarajan** [comment]
Ah thank you
