### ISSUE TITLE
ModuleNotFoundError: No module named 'price_parser'

### ISSUE THREAD

**Issue by ShinobiAlchemist** [Hari-Nagarajan/nvidia-bot#359]
When I run "python app.py amazon" I get the following lines:

Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from cli import cli
  File "D:\Library\Documents\GitHub\nvidia-bot\cli\cli.py", line 9, in <module>
    from stores.amazon import Amazon
  File "D:\Library\Documents\GitHub\nvidia-bot\stores\amazon.py", line 7, in <module>
    from price_parser import parse_price
ModuleNotFoundError: No module named 'price_parser'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.66

**Comment by DakkJaniels** [comment]
did you pipenv install?

**Comment by ShinobiAlchemist** [comment]
Yes. Apparently it needed to be updated.

Pipfile.lock (2a6997) out of date, updating to (750738)...

Thanks a lot!
