### ISSUE TITLE
Autobuy says there is no stock of the 2060s

### ISSUE THREAD

**Issue by zuliwa** [Hari-Nagarajan/nvidia-bot#37]
![image](https://user-images.githubusercontent.com/11893054/93768933-70339780-fc1a-11ea-8013-53aa13f6ab74.png)

**Comment by Hari-Nagarajan** [comment]
It looks like there are 2 product ids for 2060s in your region. One has stock the other doesn't.

**Comment by zuliwa** [comment]
This seems to break the code as it doesn't bring up any checkout pages
