### ISSUE TITLE
Chrome starts with a temp profile

### ISSUE THREAD

**Issue by notpentadactyl** [Hari-Nagarajan/nvidia-bot#39]
Trying to buy a 2060S seems to start chrome with a temp profile, which means that you can't really login before.
It doesn't seem to matter if chrome is running or not.

`chrome://version` from a temp chrome looks like this:
```
Command Line	"C:\Users\$USERNAME\AppData\Local\Google\Chrome\Application\chrome.exe" --disable-application-cache --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\$USERNAME\AppData\Local\Temp\scoped_dir****_******" --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox data:,
Profile Path	C:\Users\$USERNAME\AppData\Local\Temp\scoped_dir****_******\Default
```

**Comment by mike9011** [comment]
It doesn't matter.. it transfers the session etc to the script.

**Comment by notpentadactyl** [comment]
> 
> 
> It doesn't matter.. it transfers the session etc to the script.

not for me, it prompts me to login

**Comment by Hari-Nagarajan** [comment]
So this opening the cart happens 1 of 2 ways. 
1. ```webbrowser.open_new_tab(url.url)``` This just opens in your default browser, if you are already logged in, you are good to go!
2. Selenium (chromdriver), this logs in in the start of the script and then opens the cart in that same session. 

Having chromedriver use your user profile would be a bit of a nightmare because the profile could be in different places on different peoples computers and OS

**Comment by notpentadactyl** [comment]
![nvidia](https://user-images.githubusercontent.com/21175961/93781104-4afa5580-fc29-11ea-962d-2fc9827bced9.png)

**Comment by notpentadactyl** [comment]
When I open a python shell and invoke:
```
>>> import webbrowser
>>> webbrowser.open('http://google.com')
True
>>> webbrowser.open_new_tab('http://google.com')
True
```

The default chrome browser with my profile opens as expected.

**Comment by Hari-Nagarajan** [comment]
Yes. Selenium invoked chrome does not use your profile, but it doesnt matter because it then logs into your account.

**Comment by notpentadactyl** [comment]
> 
> 
> Yes. Selenium invoked chrome does not use your profile, but it doesnt matter **because it then logs into your account**.
but it doesn't...

I think the issue is: 
 "https://store.nvidia.com/DRHM/store?Action=Logout&SiteID=nvidia&Locale=**en_US**&ThemeID=326200&Env=BASE&nextAction=help"

This should use the local like e.g. `de_DE`
If I change it, the login works...

**Comment by Hari-Nagarajan** [comment]
Oh! Thanks for that, see if this fixes your issue:
https://github.com/Hari-Nagarajan/nvidia-bot/commit/18c384f2957b5b872a48b95690b88ff5e1dfb464

**Comment by notpentadactyl** [comment]
Now it looks WAY better. 👍 
```
INFO: "2020-09-21 19:03:27,506 - Signing in.
INFO: "2020-09-21 19:03:28,904 - Adding driver cookies to session
INFO: "2020-09-21 19:03:28,904 - Getting product IDs
INFO: "2020-09-21 19:03:29,865 - Closing webdriver
INFO: "2020-09-21 19:03:34,520 - We have 2 product IDs for NVIDIA GEFORCE RTX 2060 SUPER
INFO: "2020-09-21 19:03:34,521 - Product IDs: {5336532400, 5394902900}
INFO: "2020-09-21 19:03:34,522 - Checking stock for 5336532400 at 3 second intervals.
INFO: "2020-09-21 19:03:34,522 - Checking stock for 5394902900 at 3 second intervals.
INFO: "2020-09-21 19:03:35,238 - NVIDIA GEFORCE RTX 2060 SUPER (5394902900) in stock!
INFO: "2020-09-21 19:03:35,238 - Apply shopper details
INFO: "2020-09-21 19:03:35,690 - Success apply_shopper_details
INFO: "2020-09-21 19:03:35,690 - Auto buy disabled.
INFO: "2020-09-21 19:03:35,690 - Opening cart.
INFO: "2020-09-21 19:03:37,813 - None
INFO: "2020-09-21 19:03:37,814 - None
```
But it does stop on the shopping cart page, AFAIK it should go all the way to end where you only need to click `send` to complete the order, correct?

Is this maybe a issue with the translation? They should be correct for `de_de` (apart from `order_completed`), but maybe I made a mistake...

**Comment by Hari-Nagarajan** [comment]
"Auto buy disabled". Check out the diagram in the readme on how this flow works, were just opening the checkout page in that case.

**Comment by Hari-Nagarajan** [comment]
I'm not too sure about the localization and translations, its a bit of a new area for me

**Comment by notpentadactyl** [comment]
I see, makes sense, I thought it would go all the way, my bad!
