### ISSUE TITLE
Initial login is for US store should be regional

### ISSUE THREAD

**Issue by geekyed** [Hari-Nagarajan/nvidia-bot#40]
I am based in the UK, so  "https://store.nvidia.com/DRHM/store?Action=Logout&SiteID=nvidia&Locale=en_GB&ThemeID=326200&Env=BASE&nextAction=help" doesn't work for me.

Maybe based on locale, not sure on the correct url for the uk.

**Comment by DakkJaniels** [comment]
Try logging in, using your browser and post the link

**Comment by stevenhay** [comment]
I'm also based in the UK and that link works just fine for me

**Comment by geekyed** [comment]
my logins go though https://login.nvgs.nvidia.com/v1/login?key=eyJhbGciOiJIUzI1NiJ9.eyJzZSI6IlNFMjgiLCJpZCI6bnVsbCwidG9rZW5JZCI6IjI3NzI4NzE4NjI2MzQ0MjM3OSIsIm90IjoiMjc3Mjg3MTg2NDA5MTkzNDg1IiwiaWF0IjoxNjAwNzAwNTE4fQ.1UtkLo2hYlzrdgP6_qQBjC4xvOXyDSlnA0MgLYwekyE&client_id=94211547528691713&prompt=default&context=initial&theme=Light&preferred_nvidia=true&locale=en-US with captcha

**Comment by geekyed** [comment]
> I'm also based in the UK and that link works just fine for me

thats weird, are you already logged in?

**Comment by stevenhay** [comment]
![image](https://user-images.githubusercontent.com/26744309/93783699-ed173f00-fc23-11ea-8b0c-6f355f94b832.png)

It loads and I can login just fine

![image](https://user-images.githubusercontent.com/26744309/93783735-fa342e00-fc23-11ea-90ee-0f70a67e1a89.png)

**Comment by geekyed** [comment]
<img width="280" alt="Screenshot 2020-09-21 at 16 04 12" src="https://user-images.githubusercontent.com/7294869/93783832-19cb5680-fc24-11ea-8b95-7c26523ec918.png">

**Comment by stevenhay** [comment]
Can you try and checkout a 2060S on the GB website and login there, maybe you accidentally signed up to the US version?

https://www.nvidia.com/en-gb/shop/geforce/?page=1&limit=9&locale=en-gb&gpu=RTX%202060%20SUPER&gpu_filter=RTX%203090~1,RTX%203080~14,RTX%203070~1,TITAN%20RTX~1,RTX%202080%20Ti~19,RTX%202080%20SUPER~43,RTX%202080~22,RTX%202070%20SUPER~53,RTX%202070~44,RTX%202060%20SUPER~27,RTX%202060~70,GTX%201660%20Ti~68,GTX%201660%20SUPER~17,GTX%201660~20,GTX%201650%20Ti~9,GTX%201650%20SUPER~16,GTX%201650~98

**Comment by DakkJaniels** [comment]
I'm not sure it matters. I just VPN'd with a UK IP, and still logged in
with my US account no problem.

**Comment by DakkJaniels** [comment]
This was my URL on logout:

https://store.nvidia.com/DRHM/store?Action=Logout&SiteID=nvidia&Locale=en_GB&ThemeID=326200&Env=BASE&nextAction=help

**Comment by stevenhay** [comment]
Oh! I think I know! You likely have a GeForce account and not a store account, I had the same problem! Just go to checkout the 2060S and down the bottom of the cart page you can sign up and create an account with your billing info, then you can login to the store :)

**Comment by notpentadactyl** [comment]
I can at least confirm for Germany (or just me...) that changing it to `Locale=de_DE` now signs me in when trying to buy the 2060S, before it did not.

**Comment by Hari-Nagarajan** [comment]
Possibly related: https://github.com/Hari-Nagarajan/nvidia-bot/issues/39

18c384f#diff-1cf3dba9b1118cb0f8672d0d30f53057R507 might fix these issues.

**Comment by geekyed** [comment]
> Oh! I think I know! You likely have a GeForce account and not a store account, I had the same problem! Just go to checkout the 2060S and down the bottom of the cart page you can sign up and create an account with your billing info, then you can login to the store :)

I think you may have it! ill create one now
