### ISSUE TITLE
Bypass address suggestion not working (17:20 BST)

### ISSUE THREAD

**Issue by tashonleo** [Hari-Nagarajan/nvidia-bot#44]
Thanks for the CVV fix for GB locale. Unfortunately the "Use this address" bypass isn't working on the next page.

I hope the following info is useful for you.

Page Title: "<title>NVIDIA Online Store - Address Validation Suggestion Page</title>"

Form Container div ID: "#dr_suggestionForm"

Button:
`<input id="selectionButton" type="button" class="dr_button" value="Use this address" onclick="setDefaultRadioValuesWhenNoSuggestOption(true,false);javascript:document.suggestionForm.submit();q=false;" style="display: inline-block;">`

![Capture](https://user-images.githubusercontent.com/20631013/93795375-302bdf00-fc31-11ea-87a6-a5d7eb0b6524.PNG)

**Comment by Desync345** [comment]
Please change the following in the nvidia.py -> address_validation_page function

from
```
selenium_utils.button_click_using_xpath(
                self.driver, "//input[@id='selectionButton']"
            )
```
 to
```
selenium_utils.button_click_using_xpath(
                self.driver, "//input[@id='selectionButton']"
            ).click()
```

**Comment by tashonleo** [comment]
> Please change the following in the nvidia.py -> address_validation_page function
> 
> from
> 
> ```
> selenium_utils.button_click_using_xpath(
>                 self.driver, "//input[@id='selectionButton']"
>             )
> ```
> 
> to
> 
> ```
> selenium_utils.button_click_using_xpath(
>                 self.driver, "//input[@id='selectionButton']"
>             ).click()
> ```

Didn't work, unfortunately.

**Comment by Desync345** [comment]
Working for me
Did you set the following in the autobuy_config.json?

 "BYPASS_ADDRESS_SUGGESTION":true

**Comment by tashonleo** [comment]
Yep. Just double-checked.

**Comment by tashonleo** [comment]
Seems to be fixed following @mihaiparvu commits. Thanks!
