### ISSUE TITLE
Nvidia Captcha

### ISSUE THREAD

**Issue by Hari-Nagarajan** [Hari-Nagarajan/nvidia-bot#45]
Post your thoughts and ideas on how we want to deal with the different ways nvidia could implement a captcha. They currently do not have one.

**Comment by GreenLEDPlugins** [comment]
You could take the user up to the captcha and then take back over once it is finished but you won't achieve full automation. 

Another option would be using the digital river API completely but I think that's what NVIDIA is looking for when they cancel orders.

**Comment by WhatUpGit** [comment]
If stock appears but autobuy is unsuccessful (fue to captcha or change in flow), can we have it open the chrome session/browser to where it landed? Or fallback to non-autobuy flow (just add to cart)

I’m just thinking if they update site and stock at same time we won’t have time to update before stock is out

**Comment by stopmoclay** [comment]
2Captcha implementation maybe

**Comment by shaungupta** [comment]
There are some python capture packages, dunno how good/easy they are though:

- https://pypi.org/project/python-anticaptcha/
- https://pypi.org/project/captcha/

**Comment by freejack** [comment]
Depends on whether it shows up for everyone or only rate-limited clients.  If it's everyone the we have to manually intervene and to do so quickly, it would help to have an audible alarm like some other inventory monitors.  Notification services are useful but having it play on the desktop would be most effective.

**Comment by GoldDust69** [comment]
I have a little experience with using captcha solutions. The problem with using a solution like this is once a solution is found, there is often no submit button and you need to execute a script with the path to the callback function. Finding that may prove troublesome unless you know how to write something to automatically find that path - which is possible but beyond me.

**Comment by Desync345** [comment]
From an Nvidia Q/A

What changes are you making to the NVIDIA Store moving forward?

As with many other etailers, the NVIDIA Store was also overrun with malicious bots and resellers. To combat this challenge we have made the following changes: we moved our NVIDIA Store to a dedicated environment, with increased capacity and more bot protection. We updated the code to be more efficient on the server load. We integrated CAPTCHA to the checkout flow to help offset the use of bots. We implemented additional security protections to the store APIs. And more efforts are underway.

**Comment by sonic41592** [comment]
Is it possible to use the Chrome extension Buster: Captcha Solver for Humans?

**Comment by ChangsinPark** [comment]
Does Paypal payment method works well from a previous update about Nvidia?

**Comment by ChangsinPark** [comment]
> From an Nvidia Q/A
> 
> What changes are you making to the NVIDIA Store moving forward?
> 
> As with many other etailers, the NVIDIA Store was also overrun with malicious bots and resellers. To combat this challenge we have made the following changes: we moved our NVIDIA Store to a dedicated environment, with increased capacity and more bot protection. We updated the code to be more efficient on the server load. We integrated CAPTCHA to the checkout flow to help offset the use of bots. We implemented additional security protections to the store APIs. And more efforts are underway.

No more just let me get 2 of them.

**Comment by TerryFrench** [comment]
ML captcha solving is likely a potential solution. We need to see them first. For instance the one from Amazon seem very simple: white background, rotation and little overlap of black letters.

**Comment by TerryFrench** [comment]
If we can save the captcha images each time we get them, we can rather quickly get a list of images (and manually generate the text for them). 
I'll take a look at this https://github.com/FSecureLABS/captcha22/ as this seems the most promising I have seen, and claims to be able to train a model with small numbers.  I'll see if I can install that. I suspect a docker container install of the final server (with trained model) would allow a "portable" local captcha solving code. if we get over say 60% accuracy, that should take care of what is needed (can retry a couple of times likely)

**Comment by paulclou** [comment]
[Deep-CAPTCHA](https://arxiv.org/pdf/2006.08296.pdf) shows a 98% accuracy for text-based captcha generated from ImageCaptcha (avoided manual labeling). However this is limited by 1) specific captcha type and 2) fixed number of characters. Commercial captcha services would almost certainly kill this approach.

Fastest and easiest methods to implement are most likely
- Show user an image and prompt for a response. See [JDownloader](https://support.jdownloader.org/Knowledgebase/Article/View/jd-opens-my-browser-to-display-captchas) for demonstration.
- Commercial services, [approx $1/1000 solves](https://anti-captcha.com/mainpage). I suspect professional scalpers use this.

**Comment by Hari-Nagarajan** [comment]
https://github.com/Hari-Nagarajan/nvidia-bot/pull/76

Or they just do this.

**Comment by jeremych1000** [comment]
@Hari-Nagarajan is that workaround still valid? 

I saw [this](https://www.reddit.com/r/nvidia/comments/ixtno6/nvidia_added_captcha_to_the_checkout_page/) but both your PR and that reddit post was 15 hours ago.

**Comment by notpentadactyl** [comment]
The captcha (google reCAPTCHA) is at the very last page before you "send".

**Comment by Hari-Nagarajan** [comment]
Workaround is still valid, a bunch of people in the discord were testing it with 2060s because they didn't believe and now they have orders in lol
