### ISSUE TITLE
Amazon Checkout Issue

### ISSUE THREAD

**Issue by SauceGodPluto** [Hari-Nagarajan/nvidia-bot#47]
The whole process works fine but when amazon loads up in the newer browser and logs in it then asks for email confirmation or a captcha, the script then does an auto refresh which ruins the whole script since when it would find the thing in stock instead of checking out it'd just click on sign in again.

**Comment by jdkennedy45** [comment]
Same. It opens new browser and attempts to login but a verification pops up to your mobile, and the program instantly skips that so it never logs into Amazon. I also have 2-verification disabled in Amazon. Maybe I should just make a new Amazon account.

**Comment by Hari-Nagarajan** [comment]
Try this for me:
1. Run the script for amazon
2. Let it skip the login due to captcha etc
3. Once its refreshing the product page, open a new tab and sign in manually on the new tab

**Comment by jdkennedy45** [comment]
Yep that works for now.

**Comment by Dinzy3** [comment]
I tried the above and it does not work.  As soon as I sign in on the new tab the browser window crashes and the script fails.  What works for me is to add a 120s delay after the login - I just changed the default one from 3 to 120.  This gives me more than enough time to do the login and then paste the link to the product back in the window.

**Comment by johnconnor2020** [comment]
> I tried the above and it does not work. As soon as I sign in on the new tab the browser window crashes and the script fails. What works for me is to add a 120s delay after the login - I just changed the default one from 3 to 120. This gives me more than enough time to do the login and then paste the link to the product back in the window.

Where can I edit the delay?

**Comment by Dinzy3** [comment]
in the amazon.py which is in the stores folder.  See below.  

class Amazon:
    def __init__(self, username, password, debug=False):
        self.notification_handler = NotificationHandler()
        if not debug:
            chrome_options.add_argument("--headless")
        self.driver = webdriver.Chrome(
            executable_path=binary_path, options=options, chrome_options=chrome_options
        )
        self.wait = WebDriverWait(self.driver, 10)
        self.username = username
        self.password = password
        self.login()
        time.sleep(120)   <--  Change this
