### ISSUE TITLE
Feature Request: Notification when adding to cart during autobuy?

### ISSUE THREAD

**Issue by tashonleo** [Hari-Nagarajan/nvidia-bot#51]
Current behaviour is that when autobuy is enabled, we only get notifications if checkout completes.

Would it be possible to add a notification trigger on adding item to cart even if autobuy is enabled? This would help to alert us if autobuy fails for whatever reason (captcha/timeouts etc)

**Comment by Hari-Nagarajan** [comment]
Ok

**Comment by Hari-Nagarajan** [comment]
Done
