### ISSUE TITLE
SSL Error normal?

### ISSUE THREAD

**Issue by Flight777** [Hari-Nagarajan/nvidia-bot#60]
Hi again,

Just woke up this morning to a surprise of another new version, you are on fire! :) You should get a donate button up, if this gets me the card, I'll happily buy you a coffee.

There is one thing I want to double check. With the new logic, I'm getting an SSL error, is this expected?

![image](https://user-images.githubusercontent.com/5236143/93852211-eafbc180-fcb1-11ea-9666-8fe568faf881.png)

**Comment by anivdas** [comment]
did you do a "pipenv install" after pulling the new code?

**Comment by Flight777** [comment]
Yep, heard from another user he had the same error.

**Comment by johnconnor2020** [comment]
Also getting this error on de_de

![image](https://user-images.githubusercontent.com/71572498/93883491-eb13b580-fce1-11ea-80ef-32f9b76a3b62.png)
