### ISSUE TITLE
nvidia store script errors out after running for 12-15 mins (randomly).

### ISSUE THREAD

**Issue by anivdas** [Hari-Nagarajan/nvidia-bot#61]
![Capture](https://user-images.githubusercontent.com/13469275/93856684-000b2d00-fc7f-11ea-8224-0261039a3def.JPG)

**Comment by stevenhay** [comment]
happening to me, too!

**Comment by johnconnor2020** [comment]
I get the same error in addition to:

```
DEBUG: "2020-09-22 07:48:41,289 - Error: [{'relation': 'https://developers.digitalriver.com/v1/shoppers/CartsResource', 'code': 'inventory-unavailable-error', 'description': 'Wir müssen Ihnen leider mitteilen, dass NVIDIA GEFORCE RTX 3080 gegenwärtig nicht vorrätig ist und daher nicht zu Ihrem Warenkorb hinzugefügt werden kann. Wir möchten uns für alle Unannehmlichkeiten entschuldigen, die Ihnen möglicherweise hierdurch entstanden sind.'}]
DEBUG: "2020-09-22 07:48:44,322 - Checking if item (5438792300) in stock
```

**Comment by nefar10us** [comment]
Can confirm I just got this error.

Have been running the script for nearly a day now though without any error, so perhaps it was on NVIDIA's side?

**Comment by stevenhay** [comment]
I would imagine so yeah, I've been running it for a while too. Maybe a
change to help stop bot scripts from working continuously.

**Comment by zeldridge** [comment]
I had a similar error. I made sure I had the latest push and did a pipenv install and I have been good ever since.

**Comment by stevenhay** [comment]
haven't changed a thing and it's working fine again now, I guess it was something to do with the store apis

**Comment by anivdas** [comment]
Seems to be working fine now. Will monitor and close if no issues persist.

**Comment by kvndhrty** [comment]
I got the same issue this morning and it is continuing through the afternoon. I added noise to my refresh delay (just a random uniform variable), since they may just be looking for periodic refreshes.

**Comment by anivdas** [comment]
Thanks for that tip! I will try adding some jitter and see if it helps :)

**Comment by Hari-Nagarajan** [comment]
> I get the same error in addition to:
> 
> ```
> DEBUG: "2020-09-22 07:48:41,289 - Error: [{'relation': 'https://developers.digitalriver.com/v1/shoppers/CartsResource', 'code': 'inventory-unavailable-error', 'description': 'Wir müssen Ihnen leider mitteilen, dass NVIDIA GEFORCE RTX 3080 gegenwärtig nicht vorrätig ist und daher nicht zu Ihrem Warenkorb hinzugefügt werden kann. Wir möchten uns für alle Unannehmlichkeiten entschuldigen, die Ihnen möglicherweise hierdurch entstanden sind.'}]
> DEBUG: "2020-09-22 07:48:44,322 - Checking if item (5438792300) in stock
> ```

This is not an error

**Comment by kvndhrty** [comment]
> Thanks for that tip! I will try adding some jitter and see if it helps :)

I'm still getting whacked!
