### ISSUE TITLE
Autobuy disabled, but card details inputted.

### ISSUE THREAD

**Issue by nefar10us** [Hari-Nagarajan/nvidia-bot#65]
Filled out my NVIDIA profile, complete with a billing and shipping address, in addition to my card number.
However still getting this error on launching the bot:

`ERROR: "2020-09-22 19:53:02,619 - No payment option on account or missing CVV. Disable Autobuy`

My autobuy_config.json file looks like this:

```
{
  "NVIDIA_LOGIN": "[redacted]",
  "NVIDIA_PASSWORD": "[redacted]",
  "FULL_AUTOBUY":false,
  "CREDITCARD_NUMBER":"XXXX XXXX XXXX 87XX",
  "CREDITCARD_EXP":"07/20XX",
  "CREDITCARD_SECURITY_CODE":"XXX",
  "AUTOBUY_COUNTRY_SELECT":"",
  "BYPASS_ADDRESS_SUGGESTION":false
}
```

Login works fine otherwise.
Attached is the screenshot of what my NVIDIA profile looks like.
<img width="814" alt="Screen Shot 2020-09-22 at 7 53 31 pm" src="https://user-images.githubusercontent.com/71644595/93868669-4fbb1a00-fcba-11ea-96ef-86708d4dea47.png">

**Comment by shiftstealth** [comment]
Seems like you're using an older version. The newer version relies on having a saved payment method

**Comment by nefar10us** [comment]
> Seems like you're using an older version. The newer version relies on having a saved payment method

Still do have a saved payment method, though.

**Comment by andirew** [comment]
Check the new config template, should have updated config requirements that require u to only put in ur CCV.

**Comment by Hari-Nagarajan** [comment]
Please fix your config file: https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/autobuy_config.template_json

**Comment by nefar10us** [comment]
That fixed it. 
Closed!
