### ISSUE TITLE
Add test flag for notifications

### ISSUE THREAD

**Issue by nefar10us** [Hari-Nagarajan/nvidia-bot#66]
Would be great to test notification support so that we can be sure they're setup correctly :)

**Comment by johnconnor2020** [comment]
Whats a test flag?
I think it would better to get a discord or telegram notification when the bot crashes

**Comment by nefar10us** [comment]
Be able to test notification systems.
So by -test, it would send a notification for the enabled services (Twillo, Twitter, Discord, etc.)

**Comment by johnconnor2020** [comment]
Great idea!

**Comment by geekyed** [comment]
Is there any value in this over just running the nvidia script with a 2060S?

**Comment by awrel34** [comment]
You already can run commands below to test all configured notification handlers:
pipenv install 
pipenv run python app.py test-notifications

**Comment by geekyed** [comment]
As per the above this has been implemented.
