### ISSUE TITLE
Buying 2060S not working in de_de (even though its on stock on website)

### ISSUE THREAD

**Issue by johnconnor2020** [Hari-Nagarajan/nvidia-bot#67]
Justin reported this issue on the discord

I was able to recreat it.

It says "still working"

Even though it should alert us that its in stock and / or buy it.

https://discordapp.com/channels/756730877509369906/756730877785931935/757927220999225424

![](https://media.discordapp.net/attachments/756730877785931935/757927218742689812/unknown.png)

**Comment by johnconnor2020** [comment]
According to Dave Ramos also not working in es-es

https://discordapp.com/channels/756730877509369906/756730877785931935/757928895281496085

**Comment by notpentadactyl** [comment]
@johnconnor2020  Make sure you are already logged in to the nvidia store in your browser: go to (for Germany) https://store.nvidia.com/DRHM/store?Action=Logout&SiteID=nvidia&Locale=de_de&ThemeID=326200&Env=BASE&nextAction=help and login, then run the script again, it should work.

**Comment by johnconnor2020** [comment]
Tried it, still only says "Still working" 
even though its in stock

**Comment by notpentadactyl** [comment]
@johnconnor2020 works just fine for me (don't mind that it looks different)

![2060s](https://user-images.githubusercontent.com/21175961/93882789-fca88d80-fce0-11ea-8f5a-c71a2c0af3d3.png)

**Comment by johnconnor2020** [comment]
@notpentadactyl Weird, I tried it again and it works now. However Im also getting three lines of cord with an error about some handshake failed:

![image](https://user-images.githubusercontent.com/71572498/93883230-92dcb380-fce1-11ea-9731-628e7a98a30a.png)

**Comment by notpentadactyl** [comment]
Possible related https://github.com/Hari-Nagarajan/nvidia-bot/issues/60
