### ISSUE TITLE
Any chance NVIDIA will change their API keys on Monday?

### ISSUE THREAD

**Issue by johnpanos** [Hari-Nagarajan/nvidia-bot#7]
Not really an issue with the code, but what are your thoughts on the change NVIDIA might change the Digital River API key?

**Comment by mihaiparvu** [comment]
Hmm, do you have any source on this?

**Comment by Hari-Nagarajan** [comment]
I'll be watching it, hopefully it wont happen

**Comment by Hari-Nagarajan** [comment]
Luckily its an easy change for us if that does happen

**Comment by johnpanos** [comment]
Any chance of an auto API key updater after today's fiasco?

This launch is terrible...
