### ISSUE TITLE
Question about adding international amazon stores

### ISSUE THREAD

**Issue by johnconnor2020** [Hari-Nagarajan/nvidia-bot#70]
I copied the amazon.py and edited to make it work for amazon.co.uk and amazon.de

I named them:

amazonde.py
amazoncouk.py

However when typing

`python. app.py amazonuk`

I get an error saying:

`Usage: app.py [OPTIONS] COMMAND [ARGS]...
Try 'app.py --help' for help.
Error: No such command 'amazonuk'.`

How can I launch those files?

**Comment by jeremych1000** [comment]
Add corresponding code to `cli/cli.py`

**Comment by Hari-Nagarajan** [comment]
I think a better way would be to make a country parameter to the amazon class
https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/stores/amazon.py#L19
and then add the parameters to: https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/cli/cli.py#L63-L70

**Comment by Hari-Nagarajan** [comment]
I've gotten these 2 stores working now.
