### ISSUE TITLE
Issue with it_it locale

### ISSUE THREAD

**Issue by tonienri** [Hari-Nagarajan/nvidia-bot#73]
Hi there. Wanted to try the Italian locale but it wouldn't autocomplete the login info or proceed to the next pages.
Found out that you're waiting for the page title and the Italian page titles were incorrect. 
Here's the right titles to implement into nvidia.py:
>     "it_it": {
>         "signed_in_help": "NVIDIA Negozio Online - Guida",
>         "checkout": "NVIDIA Negozio Online - Vai alla cassa",
>         "verify_order": "NVIDIA Negozio Online - Verifica ordine",
>         "address_validation": "NVIDIA Negozio Online - Pagina di suggerimento per la validazione dell'indirizzo",
>         "order_completed": "NVIDIA Negozio Online - Ordine completato",
>     },

Hope it helps :)

**Comment by Hari-Nagarajan** [comment]
Fixed: https://github.com/Hari-Nagarajan/nvidia-bot/commit/6d362e871ec1657f3a9fd6f58754cd34fabcf202

Related: https://github.com/Hari-Nagarajan/nvidia-bot/issues/34

**Comment by Hari-Nagarajan** [comment]
Have you
