### ISSUE TITLE
Alpha 403 checkout error

### ISSUE THREAD

**Issue by packetsss** [Hari-Nagarajan/nvidia-bot#762]
**Describe the bug**
Every time turbo-initiate runs, it returns 403, even on a test (on stock) item in `amazon_checkout.py`

**To Reproduce**
Add a test item to config, run the script.

**Expected behavior**
It will be stuck at `turbo_initiate` while loop since `aio_post` returns `None` for `text`

**Debug outputs**
I've printed out input and output of the `aio_post` function:

**client**: 
<aiohttp.client.ClientSession object at 0x000001FA033C6910>

**url**: 
https://smile.amazon.com/checkout/turbo-initiate?ref_=dp_start-bbf_1_glance_buyNow_2-1&pipelineType=turbo&weblab=RCX_CHECKOUT_TURBO_DESKTOP_NONPRIME_87784&temporaryAddToCart=1

**data**: 
{'offerListing.1': 'ELVfZJ1pDQtq0wclWJdKk110iRqVBJQ5%2B0dTOMT1lWnURKgxXQAw7paXxS5cGf72s%2FyxQL6iy4E%2FSQhd6r%2BCR%2BpAQ5%2Fvfq%2BSfgkfdXa0nZq9NYZetiblt0kasYikbUrnQX3sjPENHiqVh1ksJgzDqg%3D%3D', 'quantity.1': '1'}

**`resp` in `aio_post`**:
<ClientResponse(https://smile.amazon.com/checkout/turbo-initiate?ref_=dp_start-bbf_1_glance_buyNow_2-1&pipelineType=turbo&weblab=RCX_CHECKOUT_TURBO_DESKTOP_NONPRIME_87784&temporaryAddToCart=1) [403 Forbidden]>
<CIMultiDictProxy('Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Fri, 07 May 2021 17:02:35 GMT', 'x-amz-rid': 'H0GT8Q20R1JC2ZMN06X7', 'Set-Cookie': 'session-id=143-1882144-4090202; Domain=.amazon.com; Expires=Tue, 01-Jan-2036 08:00:01 GMT; Path=/', 'Set-Cookie': 'session-id-time=2082787201l; Domain=.amazon.com; Expires=Tue, 01-Jan-2036 08:00:01 GMT; Path=/', 'Set-Cookie': 'session-token="M5HwmuPpPipQzaISOG7d2pJ73dPqW5odKydw7+59srTqb7YtB76UJPvPFbPJ/fTJRQ7qyoM37/OldbyABwkE0lJmQe2MD+F+j8I5DJekw7o6z9Qmv5Bj1tK+/QYQlnKTCjNOBRG01Bf/BylVW9pXwqpjEs2YjYQ3z+OgWngjoWZaQ8Vx88rRWKhEXMXhNGYtwxldUE/uxsoH6Iti/hZD9w=="; Version=1; Domain=.amazon.com; Max-Age=462380246; Expires=Tue, 01-Jan-2036 08:00:01 GMT; Path=/', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy-Report-Only': "default-src https://*.amazon.com https://*.media-amazon.com https://*.ssl-images-amazon.com https://*.amazon-adsystem.com; script-src https://*.amazon.com https://*.media-amazon.com https://*.ssl-images-amazon.com https://*.amazon-adsystem.com 'unsafe-inline' 'unsafe-eval'; style-src https://*.amazon.com https://*.media-amazon.com https://*.ssl-images-amazon.com https://*.amazon-adsystem.com 'unsafe-inline'; report-uri /1/batch/2/OE/mid=ATVPDKIKX0DER:sid=143-1882144-4090202:rid=H0GT8Q20R1JC2ZMN06X7:sn=smile.amazon.com", 'x-amz-checkout-requestid': 'H0GT8Q20R1JC2ZMN06X7', 'Cache-Control': 'no-cache, max-age=0, must-revalidate, no-store', 'X-UA-Compatible': 'IE=edge,chrome=1', 'Vary': 'Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'x-sdch-encode': '0', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 390b284b93b535130c65850f2530b95c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'LAX50-C3', 'X-Amz-Cf-Id': 'ZnEmPvMq_YqvITbi6QJ22-e_QolvvIH2JlfhuniMpyfz1g9KfPYN0w==')>
- I don't think `text` is a key in this huge dict, so it explains why `resp.text` is nothing, I don't know what the actual dict looks like tho.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 0.7.0a2

**Comment by DakkJaniels** [comment]
I think the data needs to be submitted as part of the url, something like: url = url + '&offerListing.1=' + data['offerListing.1']+'&quantity.1=1' and not submit the data.

>I don't think text is a key in this huge dict, so it explains why resp.text is nothing, I don't know what the actual dict looks like tho.

The code says `resp.text()`, which is correct as it is a method of the aiohttp response class.

**Comment by mbbush** [comment]
This seems to be caused by a missing token in the request header. Please let me know if #760 fixes this issue for you.

**Comment by pyj2001** [comment]
@mbbush It does, that's why I closed this issue. Thanks Squig!!

**Comment by TheJohnnyPitz** [comment]
@mbbush I had the same issue and this fixes it for me too. Thank you!
