### ISSUE TITLE
Add UK stores

### ISSUE THREAD

**Issue by iKreateCode** [Hari-Nagarajan/nvidia-bot#78]
Add UK stores such as Scan.co.uk and Overclockers.co.uk

**Comment by darek292** [comment]
There is very little point adding these 2 since they had pre-orders enabled (and OCUK still does). It's only going to add value for those that drop cards and not those that allow pre-orders.

**Comment by geekyed** [comment]
Also in the UK here and wont be using this, OCUK are pre ordering without queue numbers or time, so is pointless.
Both of them did some pretty nasty price increasing 10 minutes after launch.
