### ISSUE TITLE
Amazon cookies and session

### ISSUE THREAD

**Issue by astateofmind01** [Hari-Nagarajan/nvidia-bot#81]
Bestbuy uses --user-data-dir option and it stores the cookies, i don't need to login next time when i start the app.

But amazon doesn't. I added --user-data-dir option but still doesn't hold the info...

**Comment by jbmccall** [comment]
i think the issues is due to the element name tag, currently listed as "By.NAME, "placeYourOrder1"

should be 
"By.NAME, "place-order"
