### ISSUE TITLE
Command line parameter for Selenium to block image loading

### ISSUE THREAD

**Issue by Camology** [Hari-Nagarajan/nvidia-bot#83]
As discussed on the discord, add a command line parameter that when passed will enable these two lines in Selenium_utils

```
prefs = {"profile.managed_default_content_settings.images": 2}
chrome_options.add_experimental_option("prefs", prefs)
```

**Comment by dagzyx** [comment]
#84 i just opened a pull request for this, only for the amazon bot atm though

**Comment by Camology** [comment]
Easy to expand if you want to, but instead should extrapolate to an app.py --command if possible, easier to manage

**Comment by Hari-Nagarajan** [comment]
Merged PR
