### ISSUE TITLE
Amazon timeout error after moving past "Buy Now" click

### ISSUE THREAD

**Issue by jbmccall** [Hari-Nagarajan/nvidia-bot#88]
testing on random asins, once an item is found to be in-stock and at or below the correct price, there is a timeout that occurs after but now is clicked.

Log shows "DEBUG: "2020-09-22 22:50:43,386 - Went to check out page."

(nvidia-bot-master-z-k4VtVW) nvidia-bot-master>log4net:ERROR Object type [log4net.Appender.FileAppender] is not assignable to type [log4net.Appender.FileAppender+LockingModelBase]. There are no acceptable type conversions.
log4net:ERROR Failed to create object to set param: lockingModel
log4net:ERROR Object type [log4net.Appender.FileAppender] is not assignable to type [log4net.Appender.FileAppender+LockingModelBase]. There are no acceptable type conversions.
log4net:ERROR Failed to create object to set param: lockingModel

**Comment by jbmccall** [comment]
i think the issues is due to the element name tag, currently listed as "By.NAME, "placeYourOrder1"

should be 
"By.NAME, "place-order"

**Comment by jbmccall** [comment]
this seems to be related to the time it takes for the modal pop-up, task times out before the button id is avaialble to click

**Comment by zaneerikson** [comment]
+1 Getting this issue as well.
