### ISSUE TITLE
Implement Telegram Message

### ISSUE THREAD

**Issue by Flight777** [Hari-Nagarajan/nvidia-bot#9]
If I was good at Python I would do it myself, but I've look into it and am failing at the moment. Time is scarce in order to get a RTX 3080, so maybe you can do it much quicker:

Would it be possible to let a Telegram Bot send a message? It very easy to create your own bot, then the script would only need the API and the chatid (which chat or group it needs to send the message to).

**Comment by mihaiparvu** [comment]
Yes, I have the code for sending messages with Telegram from a different project. I can make a PR for this tommorow.

**Comment by Flight777** [comment]
Cool, thanks a lot for your quick response :) You at least give us a fighting chance again the scalpers. Thanks very much for putting all the effort in it!!

**Comment by Hari-Nagarajan** [comment]
@mihaiparvu has implemented t his.

**Comment by Flight777** [comment]
Thanks for the fast turnaround! But I'm having an issue getting it to work:

![image](https://user-images.githubusercontent.com/5236143/93719950-3749e300-fb86-11ea-9ce4-1a83ef0a779d.png)

![image](https://user-images.githubusercontent.com/5236143/93719974-55174800-fb86-11ea-8b78-1050d7661229.png)

Maybe something todo with the "-" chatid? (there are groupids in Telegram)

**Comment by mihaiparvu** [comment]
Missing comma at end of line 2.

**Comment by mihaiparvu** [comment]
@Flight777 it was fixed in https://github.com/Hari-Nagarajan/nvidia-bot/commit/9e73f289391b7984b4d0ca41fd13478df0626332.
