### ISSUE TITLE
Nvidia 3090 no product ids

### ISSUE THREAD

**Issue by handzelrm** [Hari-Nagarajan/nvidia-bot#93]
Does not look like api can find rtx 3090 after nvidia made changes to their site.

**Comment by DakkJaniels** [comment]
What changes? Can you further describe this issue?

**Comment by shaungupta** [comment]
The 3090 product ids were never available. They will only become available at launch (it was the same with the 3080).

**Comment by Hari-Nagarajan** [comment]
RTX 3090 product ids havent been added to the site yet, it will pick them up when they are added
